In [1]:
from affro.core import run_affro
from affro.core import matchings_affro
from affro.helpers.functions import *
from affro.helpers.create_input import create_df_algorithm

import pandas as pd
import ast

def evaluate_micro(df, col):
    dix = {}
    true_pos = []
    false_pos = []
    false_neg = []  
    
    for i in range(len(df)):
        if len(df[col].iloc[i]) == 0:
            true_pos.append(0)
            false_pos.append(0)
            false_neg.append(len(df['curated'].iloc[i]))

        else:
            correct_i = 0 
            incorrect_i = 0 
            for x in df[col].iloc[i]:
                if x in df['curated'].iloc[i]:
                    correct_i = correct_i + 1
                else:
                    incorrect_i = incorrect_i + 1
                    
            
            true_pos.append(correct_i)
            false_pos.append(incorrect_i)
            false_neg.append( len(df['curated'].iloc[i]) - correct_i)


       
    df['TP'+"_"+col] = true_pos
    df['FP'+"_"+col] = false_pos
    df['FN'+"_"+col] = false_neg

    total_tp = df["TP"+"_"+col].sum()
    total_fp = df["FP"+"_"+col].sum()
    total_fn = df["FN"+"_"+col].sum()

    # Micro Precision, Recall, and F1-Score
    micro_precision = total_tp / (total_tp + total_fp)
    micro_recall = total_tp / (total_tp + total_fn)

    micro_f1_score = 2 * (micro_precision * micro_recall) / (micro_precision + micro_recall)

   

    dix['precision'] = micro_precision
    dix['recall'] = micro_recall
    dix['f1_score'] = micro_f1_score


    
    return dix

def overall(ev1, ev2):
    return [(ev1['precision']+ev2['precision'])/2, (ev1['recall']+ev2['recall'])/2 , (ev1['f1_score']+ev2['f1_score'])/2]

In [2]:
dix_name['ntua']

[{'id': 'https://ror.org/00wy14q17',
  'city': ['taipei'],
  'country': ['taiwan'],
  'label': None,
  'first': 'n'},
 {'id': 'https://ror.org/03cx6bg69',
  'city': ['athens'],
  'country': ['greece'],
  'label': None,
  'first': 'n'}]

In [2]:
create_df_algorithm('desy, germany',4)

['desy, germany',
 'desy, germany',
 [{'index': 0, 'keywords': 'desy', 'category': 'Acronyms'}],
 ['germany'],
 ['desy']]

In [2]:
run_affro('ntua, greece')

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/03cx6bg69',
  'name': 'National Technical University of Athens',
  'confidence': 1.0,
  'status': 'active',
  'country': ['greece']}]

In [64]:
uoa = pd.read_csv('/Users/myrto/Documents/openAIRE/14. countries/2. greece/SCOPUS_harvest_HEAL-Link institutions/uoa.csv')

In [66]:
uoa.groupby('year').size().sort_values(ascending=False)

year
2025    6422
2022    6053
2021    6022
2024    5933
2023    5889
2020    5218
2019    4605
2018    4395
2017    4074
2016    3659
2015    3328
2026    3014
dtype: int64

In [41]:
file = pd.read_csv("/Users/myrto/Downloads/openaire IDs all pubs_2026-06-22 04_47_19 PM (1).csv")

In [9]:
file = pd.read_csv("/Users/myrto/Downloads/openaire IDs all peer-rev pubs_2026-06-22 08_48_38 PM.csv")

In [43]:
file['name'] = [dix_id[x]['name'] for x in file['org_id']]

In [61]:
file[file['org_id'] == 'https://ror.org/04h36ea57']

,org_id,only_oaire,both,only_scopus,name
65,https://ror.org/04h36ea57,9685,0,0,Alexander Technological Educational Institute ...

In [62]:
file[file['org_id'] =='https://ror.org/00708jp83']

,org_id,only_oaire,both,only_scopus,name
23,https://ror.org/00708jp83,5078,4607,289,International Hellenic University

In [49]:
file[file['org_id'] == 'https://ror.org/04v4g9h31']

,org_id,only_oaire,both,only_scopus,name
181,https://ror.org/04v4g9h31,44649,16413,1247,University of Thessaly

In [48]:
file[file['both'] == 0][60:90]

,org_id,only_oaire,both,only_scopus,name
63,https://ror.org/057pnws69,383,0,0,Centre for Planning and Economic Research
65,https://ror.org/04h36ea57,9685,0,0,Alexander Technological Educational Institute ...
66,https://ror.org/035e8e276,461,0,0,Thriasio General Hospital of Elefsina
67,https://ror.org/02kpyrm37,1385,0,0,Ippokrateio General Hospital of Thessaloniki
68,https://ror.org/04d84av86,30,0,0,Ministry of National Defence
69,https://ror.org/05grd6s28,286,0,0,South East European Research Centre
70,https://ror.org/034tvnv21,37,0,0,Hellenic Parliament
71,https://ror.org/04cdzwd37,179,0,0,Merchant Marine Academy
72,https://ror.org/05e536w67,532,0,0,Institute of Molecular Medicine and Biomedical...
73,https://ror.org/036d9xe15,17,0,0,Ceramics and Refractories Technological Develo...
75,https://ror.org/01n47re51,2,0,0,Paragon (Greece)
76,https://ror.org/01zy7ja20,83,0,0,Earthquake Planning and Protection Organization
77,https://ror.org/05kwk4552,295,0,0,American School of Classical Studies at Athens
78,https://ror.org/03xbkmz44,1192,0,0,Athens Naval & Veterans Hospital
80,https://ror.org/01mw24p94,9685,0,0,Technological Educational Institute of Central...
81,https://ror.org/03vkake80,1391,0,0,The American College of Greece
82,https://ror.org/04e8qdj27,6,0,0,Hellenic Register of Shipping
83,https://ror.org/01mymm084,64300,0,0,Technological Educational Institute of Western...
84,https://ror.org/01v15pf03,27,0,0,Hellenic Telecommunications and Post Commissio...
86,openorgs____::0000103316,0,0,23,National Documentation Centre (EKT) / National...
87,https://ror.org/03ya9h906,19,0,0,National Library of Greece
88,https://ror.org/00tq5n859,45,0,0,Institute of Nuclear & Radiological Sciences a...
89,https://ror.org/03kbqak87,38,0,0,Ellinogermaniki Agogi
90,https://ror.org/02c8rf527,1,0,0,Synthesis and Research (Greece)
91,https://ror.org/01nq9yz29,20,0,0,Inasco (Greece)
92,https://ror.org/02ds0wa60,22,0,0,"Olympic Athletic Center of Athens ""Spiros Louis"""
93,https://ror.org/0419szn97,65,0,0,International Centre for Research on the Envir...
94,https://ror.org/031yp1y05,1,0,0,Loufakis (Greece)
95,https://ror.org/04056ja87,61062,0,0,Technological Educational Institute of Thessaly
96,https://ror.org/01a3n7y93,1,0,0,Advanced Management Solutions (Greece)

In [19]:
file.to_csv("/Users/myrto/Downloads/openaire IDs all pubs_2026-06-22 04_47_19 PM.csv")

In [27]:
file[file['both'] != 0].to_csv(("/Users/myrto/Downloads/all_IDs.csv"))

In [40]:
file[file['org_id'] == 'https://ror.org/00a5pe906']

,org_id,only_oaire,both,only_scopus,name
274,https://ror.org/00a5pe906,3786,4268,372,University of Western Macedonia

In [7]:
key_words

['research',
 'centro',
 'recherche',
 'uniwersytet',
 'investigacions',
 'instit',
 'istitut',
 'univ',
 'col',
 'center',
 'polytechnic',
 'tech',
 'politecnico',
 'polutekhneio',
 'prifysgol',
 'centre',
 'kentro',
 'politechnika',
 'szkola',
 'faculty',
 'school',
 'academ',
 'akadem',
 'schule',
 'ecole',
 'observ',
 'escuela',
 'escola',
 'unibertsi',
 'yliopisto',
 'instytut',
 'zentrum',
 'panepist',
 'lab',
 'scien',
 'cientific',
 'egyetem',
 'sterewacht',
 'tecnol',
 'data',
 'labora',
 'versuchsanstalt',
 'informatics',
 'vishwavidyalaya',
 'hospital',
 'clinic',
 'hopital',
 'klinik',
 'oncol',
 'medical',
 'health',
 'medicin',
 'nosokomei',
 'krankenhaus',
 'ziekenhuis',
 'spital',
 'cancer',
 'pharma',
 'therapeutics',
 'ospedale',
 'dermato',
 'gmbh',
 'company',
 'industr',
 'etaireia',
 'corporation',
 'inc',
 'ltd',
 'foundation',
 'asociation',
 'vereniging',
 'organization',
 'society',
 'group',
 'groupo',
 'grupe',
 'royal',
 'ofice',
 'trust',
 'survey',
 'museum',
 'museen',
 'library',
 'bank',
 'comision',
 'komision',
 'stiftung',
 'katholieke',
 'catholic',
 'authority',
 'forum',
 'fond',
 'transport',
 'repository',
 'knowledge',
 'district',
 'federation',
 'government',
 'municipal',
 'county',
 'council',
 'agency',
 'bundesagentur',
 'infrastructure',
 'abot',
 'squib',
 'intel',
 'motorola',
 'samsung',
 'hitachi',
 'roche',
 'google',
 'yahoo',
 'ebay',
 'novartis',
 'microsoft',
 'ibm',
 'alergan',
 'medtronic',
 'xilinx',
 'pfizer',
 'glaxosmithkline',
 'astrazeneca',
 'boehringer ingelheim',
 'demokritos',
 'siemens',
 'forth',
 'eli lily',
 'boeing',
 'alphabet',
 'johnson johnson',
 'moderna',
 'bayer',
 'huawei',
 'amazon',
 'sinopec',
 'novo nordisk',
 'sanofi',
 'amgen',
 'abvie',
 'basf',
 'toyota',
 'gilead',
 'teagasc',
 'apc microbiome',
 'nestle',
 'perkinelmer',
 'shel',
 'visteon',
 'hewlet packard',
 'fujitsu',
 'toshiba',
 'met eirean',
 'eurnex',
 'euromedica',
 'elpen',
 'laservision',
 'alkermes',
 'eth zurich',
 'riken',
 'ucd',
 'tcd',
 'nasa',
 'bgi',
 'ntt',
 'dow',
 'ustc',
 'zju',
 'pku',
 'ucas',
 'nju',
 'scu',
 'mit',
 'hust',
 'ucla',
 'uc san diego',
 'uc berkeley',
 'jhu',
 'uchicago',
 'caltech',
 'usp',
 'conicet',
 'unicamp',
 'cnr',
 'ucl',
 'csic',
 'epfl',
 'ucph',
 'tum',
 'lmu',
 'ku leuven',
 'ircs',
 'nhs',
 'discovery programe',
 'ncsr demokritos',
 'nui galway',
 'nui maynooth',
 'tu wien',
 'tu dublin',
 'athena',
 'openaire',
 'erasmus',
 'ist austria',
 'nit',
 'cern',
 'lg',
 'chu',
 'jst',
 'lumc',
 'niab',
 'conisma',
 'batele',
 'saxion',
 'wegemt',
 'scilifelab',
 'certh',
 'rwth',
 'univer',
 'labora']

In [6]:
'ntua' in key_words

False

In [8]:
run_affro("forth")

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/052rphn09',
  'name': 'Foundation for Research and Technology Hellas',
  'confidence': 1,
  'status': 'active',
  'country': ['greece']}]

In [3]:
run_affro("Dep. of Informatics & Telecommun., Athens Univ, Greece")

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/04gnjpq42',
  'name': 'National and Kapodistrian University of Athens',
  'confidence': 0.9999999999999998,
  'status': 'active',
  'country': ['greece']}]

In [4]:
create_df_algorithm("Dep. of Informatics & Telecommun., Athens univ j, Greece",4)

['dep. informatics telecomun., athens univ j, greece',
 'athens univer j, greece',
 [{'index': 0, 'keywords': 'athens univer j', 'category': 'Academia'}],
 ['greece'],
 ['univ']]

In [77]:
dix_name['univer hospital verona']

[{'id': 'https://ror.org/00sm8k518',
  'city': ['verona'],
  'country': ['italy'],
  'label': None,
  'first': 'y'}]

In [22]:
common_june =  pd.read_csv("/Users/myrto/Downloads/common_june.csv")

In [24]:
common_june['affro'] = [run_affro(x) for x in common_june['raw_affiliation_string'].to_list()]

In [26]:
for i in range(len(common_june)):
    print(i, common_june['raw_affiliation_string'].iloc[i])
    print(common_june['affro'].iloc[i])
    print("")

0 National Institute for Fusion Science (NIFS)
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/01t3wyv61', 'name': 'National Institute for Fusion Science', 'confidence': 1, 'status': 'active', 'country': ['japan']}]

1 National Institute for Fusion Science
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/01t3wyv61', 'name': 'National Institute for Fusion Science', 'confidence': 1, 'status': 'active', 'country': ['japan']}]

2 Leibniz Institute DSMZ - German Collection of Microorganisms and Cell Cultures
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02tyer376', 'name': 'Leibniz Institute DSMZ – German Collection of Microorganisms and Cell Cultures', 'confidence': 1, 'status': 'active', 'country': ['germany']}]

3 Pacific Northwest National Laboratory
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05h992307', 'name': 'Pacific Northwest National Laboratory', 'confidence': 1, 'status': 'active', 'country': ['united states']}]

4 Environmental Molecular Sciences Laboratory
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/04rc0xn13', 'name': 'Environmental Molecular Sciences Laboratory', 'confidence': 1, 'status': 'active', 'country': ['united states']}]

5 Sapienza University of Rome
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02be6w209', 'name': 'Sapienza University of Rome', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

6 National Research Council
[]

7 University of Michigan
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/00jmfr291', 'name': 'University of Michigan', 'confidence': 1, 'status': 'active', 'country': ['united states']}]

8 University of Bologna
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/01111rn36', 'name': 'University of Bologna', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

9 University of Naples Federico II
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05290cv24', 'name': 'University of Naples Federico II', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

10 University of Padua
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/00240q980', 'name': 'University of Padua', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

11 CERN, 1211 Geneva 23, Switzerland
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/01ggx4157', 'name': 'European Organization for Nuclear Research', 'confidence': 1.0, 'status': 'active', 'country': ['switzerland']}]

12 Università degli Studi di Milano – Department of Environmental Science and Policy, Milano, Italy
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/00wjc7c48', 'name': 'University of Milan', 'confidence': 1.0, 'status': 'active', 'country': ['italy']}]

13 China
[]

14 University of Milan
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/00wjc7c48', 'name': 'University of Milan', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

15 (GEUS)
[]

16 Powered by the California Digital Library University of California,USA
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/03yrm5c26', 'name': 'California Digital Library', 'confidence': 0.8728715609439696, 'status': 'active', 'country': ['united states']}]

17 University of Florence
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/04jr1s763', 'name': 'University of Florence', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

18 Wageningen University & Research
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/04qw24q55', 'name': 'Wageningen University & Research', 'confidence': 1, 'status': 'active', 'country': ['netherlands']}]

19 NamesforLife, LLC
[]

20 University of Oxford
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/052gg0110', 'name': 'University of Oxford', 'confidence': 1, 'status': 'active', 'country': ['united kingdom']}]

21 Licensee MDPI, Basel, Switzerland
[]

22 University of Cape Town
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/03p74gp79', 'name': 'University of Cape Town', 'confidence': 1, 'status': 'active', 'country': ['south africa']}]

23 Independent  - affiliation not provided to SSRN
[]

24 KU Leuven
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05f950310', 'name': 'KU Leuven', 'confidence': 1, 'status': 'active', 'country': ['belgium']}]

25 University of Pisa
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/03ad39j10', 'name': 'University of Pisa', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

26 Department of Chemistry
[]

27 Associazione Meteonetwork OdV, Milano, Italy
[]

28 Glycan & Life Systems Integration Center, Faculty of Science and Engineering, Soka University
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/003qdfg20', 'name': 'Soka University', 'confidence': 1.0, 'status': 'active', 'country': ['japan']}]

29 Chinese Academy of Sciences
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/034t30j35', 'name': 'Chinese Academy of Sciences', 'confidence': 1, 'status': 'active', 'country': ['china']}]

30 Harvard University
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/03vek6s52', 'name': 'Harvard University', 'confidence': 1, 'status': 'active', 'country': ['united states']}]

31 University of Messina
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05ctdxz19', 'name': 'University of Messina', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

32 P. R. China
[]

33 Bielefeld University
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02hpadn98', 'name': 'Bielefeld University', 'confidence': 1, 'status': 'active', 'country': ['germany']}]

34 University of Helsinki
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/040af2s02', 'name': 'University of Helsinki', 'confidence': 1, 'status': 'active', 'country': ['finland']}]

35 University of Washington
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/00cvxb145', 'name': 'University of Washington', 'confidence': 1, 'status': 'active', 'country': ['united states']}]

36 University of Milano-Bicocca
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/01ynf4891', 'name': 'University of Milano-Bicocca', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

37 Yale University
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/03v76x132', 'name': 'Yale University', 'confidence': 1, 'status': 'active', 'country': ['united states']}]

38 USA
[]

39 CPPM - Centre de Physique des Particules de Marseille - AMU - Aix Marseille Université - IN2P3 - Institut National de Physique Nucléaire et de Physique des Particules du CNRS - CNRS - Centre National de la Recherche Scientifique
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/00fw8bp86', 'name': 'Centre de physique des particules de Marseille', 'confidence': 1.0, 'status': 'active', 'country': ['france']}, {'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/035xkbk20', 'name': 'Aix-Marseille Université', 'confidence': 1.0, 'status': 'active', 'country': ['france']}, {'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/03fd77x13', 'name': 'Institut National de Physique Nucléaire et de Physique des Particules', 'confidence': 0.8944271909999159, 'status': 'active', 'country': ['france']}, {'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02feahw73', 'name': 'Centre National de la Recherche Scientifique', 'confidence': 1.0, 'status': 'active', 'country': ['france']}]

40 University of Verona
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/039bp8j42', 'name': 'University of Verona', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

41 University of Ferrara
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/041zkgm14', 'name': 'University of Ferrara', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

42 Polytechnic University of Turin
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/00bgk9508', 'name': 'Politecnico di Torino', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

43 University of North Carolina at Chapel Hill
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/0130frc33', 'name': 'University of North Carolina at Chapel Hill', 'confidence': 1, 'status': 'active', 'country': ['united states']}]

44 Stanford University
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/00f54p054', 'name': 'Stanford University', 'confidence': 1, 'status': 'active', 'country': ['united states']}]

45 LAL - Laboratoire de l'Accélérateur Linéaire - UP11 - Université Paris-Sud - Paris 11 - IN2P3 - Institut National de Physique Nucléaire et de Physique des Particules du CNRS - CNRS - Centre National de la Recherche Scientifique
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/046w3ze59', 'name': "Laboratoire de l'Accélérateur Linéaire", 'confidence': 1.0, 'status': 'inactive', 'country': ['france']}, {'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/03gc1p724', 'name': 'Laboratoire de Physique des 2 Infinis Irène Joliot-Curie', 'confidence': 1.0, 'status': 'active', 'country': ['france']}, {'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/028rypz17', 'name': 'Université Paris-Sud', 'confidence': 1.0, 'status': 'inactive', 'country': ['france']}, {'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/03xjwb503', 'name': 'Université Paris-Saclay', 'confidence': 1.0, 'status': 'active', 'country': ['france']}, {'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/03fd77x13', 'name': 'Institut National de Physique Nucléaire et de Physique des Particules', 'confidence': 0.8944271909999159, 'status': 'active', 'country': ['france']}, {'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02feahw73', 'name': 'Centre National de la Recherche Scientifique', 'confidence': 1.0, 'status': 'active', 'country': ['france']}]

46 University of Palermo
[]

47 Peking University
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02v51f717', 'name': 'Peking University', 'confidence': 1, 'status': 'active', 'country': ['china']}]

48 University of Chinese Academy of Sciences, Beijing 100049, China
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05qbk4x57', 'name': 'University of Chinese Academy of Sciences', 'confidence': 1.0, 'status': 'active', 'country': ['china']}]

49 CERN, Geneva, Switzerland
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/01ggx4157', 'name': 'European Organization for Nuclear Research', 'confidence': 1.0, 'status': 'active', 'country': ['switzerland']}]

50 University of Salerno
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/0192m2k53', 'name': 'University of Salerno', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

51 (University of Texas at Austin)
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/00hj54h04', 'name': 'The University of Texas at Austin', 'confidence': 1, 'status': 'active', 'country': ['united states']}]

52 University of Toronto
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/03dbr7087', 'name': 'University of Toronto', 'confidence': 1, 'status': 'active', 'country': ['canada']}]

53 Zhejiang University
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/00a2xv884', 'name': 'Zhejiang University', 'confidence': 1, 'status': 'active', 'country': ['china']}]

54 University of Trento
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05trd4x28', 'name': 'University of Trento', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

55 University of Rome Tor Vergata
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02p77k626', 'name': 'University of Rome Tor Vergata', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

56 University of Campania "Luigi Vanvitelli"
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02kqnpp86', 'name': 'University of Campania "Luigi Vanvitelli"', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

57 Leibniz Institute of Plant Genetics and Crop Plant Research (IPK) Gatersleben
[{'provenance': 'affro_direct', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02skbsp27', 'name': 'Leibniz-Institut für Pflanzengenetik und Kulturpflanzenforschung (IPK)', 'confidence': 1, 'status': 'active', 'country': ['germany']}]

58 IRFU - Institut de Recherches sur les lois Fondamentales de l'Univers - Université Paris-Saclay - DRF (CEA) - Direction de Recherche Fondamentale (CEA) - CEA - Commissariat à l'énergie atomique et aux énergies alternatives
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05k705z76', 'name': "Institut de Recherche sur les Lois Fondamentales de l'Univers", 'confidence': 0.9258200997725514, 'status': 'active', 'country': ['france']}, {'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/03xjwb503', 'name': 'Université Paris-Saclay', 'confidence': 1.0, 'status': 'active', 'country': ['france']}]

59 Shanghai Jiao Tong University
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/0220qvk04', 'name': 'Shanghai Jiao Tong University', 'confidence': 1, 'status': 'active', 'country': ['china']}]

60 LAPP - Laboratoire d'Annecy de Physique des Particules - IN2P3 - Institut National de Physique Nucléaire et de Physique des Particules du CNRS - USMB [Université de Savoie] [Université de Chambéry] - Université Savoie Mont Blanc - CNRS - Centre National de la Recherche Scientifique
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/04gqg1a07', 'name': 'Université Savoie Mont Blanc', 'confidence': 1.0, 'status': 'active', 'country': ['france']}, {'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/049nhh297', 'name': 'Laboratoire d’Annecy de Physique des Particules', 'confidence': 1.0, 'status': 'active', 'country': ['france']}, {'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/03fd77x13', 'name': 'Institut National de Physique Nucléaire et de Physique des Particules', 'confidence': 0.8944271909999159, 'status': 'active', 'country': ['france']}, {'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02feahw73', 'name': 'Centre National de la Recherche Scientifique', 'confidence': 1.0, 'status': 'active', 'country': ['france']}]

61 University of Trieste
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02n742c10', 'name': 'University of Trieste', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

62 University of Chinese Academy of Sciences
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05qbk4x57', 'name': 'University of Chinese Academy of Sciences', 'confidence': 1, 'status': 'active', 'country': ['china']}]

63 University of Perugia
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/00x27da85', 'name': 'University of Perugia', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

64 Imperial College London
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/041kmwe10', 'name': 'Imperial College London', 'confidence': 1, 'status': 'active', 'country': ['united kingdom']}]

65 1Department of Physics, University of Adelaide, Adelaide, Australia
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/00892tw58', 'name': 'The University of Adelaide', 'confidence': 1.0, 'status': 'inactive', 'country': ['australia']}, {'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/028g18b61', 'name': 'Adelaide University', 'confidence': 1.0, 'status': 'active', 'country': ['australia']}]

66 University of Modena and Reggio Emilia
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02d4c4y02', 'name': 'University of Modena and Reggio Emilia', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

67 Go to publication entry in University of Southern Denmark's Research Portal
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/03yrrjy16', 'name': 'University of Southern Denmark', 'confidence': 0.5345224838248487, 'status': 'active', 'country': ['denmark']}]

68 University College London
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02jx3x895', 'name': 'University College London', 'confidence': 1, 'status': 'active', 'country': ['united kingdom']}]

69 Fudan University
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/013q1eq08', 'name': 'Fudan University', 'confidence': 1, 'status': 'active', 'country': ['china']}]

70 University of Brescia
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02q2d2610', 'name': 'University of Brescia', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

71 University of Siena
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/01tevnk56', 'name': 'University of Siena', 'confidence': 1, 'status': 'active', 'country': ['italy']}]

72 University of Zurich|Zurich|Switzerland
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02crff812', 'name': 'University of Zurich', 'confidence': 1.0, 'status': 'active', 'country': ['switzerland']}]

73 Terms of use Unless otherwise specified it has been shared according to the terms for self-archiving. If no other license is stated, these terms apply:
[]

74 LUMC
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05xvt9f17', 'name': 'Leiden University Medical Center', 'confidence': 1, 'status': 'active', 'country': ['netherlands']}]

75 Russian Academy of Sciences
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05qrfxd25', 'name': 'Russian Academy of Sciences', 'confidence': 1, 'status': 'active', 'country': ['rusia']}]

76 Distributed under a Creative Commons Attribution - NonCommercial - NoDerivatives 4.0 International License
[]

77 University of Cambridge
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/013meh722', 'name': 'University of Cambridge', 'confidence': 1, 'status': 'active', 'country': ['united kingdom']}]

78 Deutsches Zentrum für Luft- und Raumfahrt
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/04bwf3e34', 'name': 'Deutsches Zentrum für Luft- und Raumfahrt e. V. (DLR)', 'confidence': 1, 'status': 'active', 'country': ['germany']}]

In [71]:
from affro.helpers.create_input import create_df_algorithm
from affro.helpers.functions import clean_string_lucky
create_df_algorithm("National Center for Scientic Research 'Demokritos', Institute of Informatics and Telecommunications,",4)

['national center scientic research demokritos, institute informatics and telecomunications,',
 'national center scientic research demokritos, instit informatics telecomunications',
 [{'index': 0,
   'keywords': 'national center scientic research demokritos',
   'category': 'Academia'},
  {'index': 1,
   'keywords': 'instit informatics telecomunications',
   'category': 'Academia'}],
 [],
 ['research', 'instit', 'informatics', 'demokritos', 'scien', 'center']]

In [50]:
for d in dix_name:
    if 'synchrotron' in d:
        print(d)

aichi synchrotron radiation center
alba synchrotron
australian synchrotron
brazilian synchrotron light labora
candle synchrotron research instit
center canadien rayonement synchrotron
ches cornel high energy synchrotron source
cornel high energy synchrotron source
deutsches elektronen synchrotron desy
europ synchrotron radiation facility
japan synchrotron radiation research instit
kyushu synchrotron light research center
narodowe center promieniowania synchrotronowego solaris
national synchrotron light source 2
national synchrotron radiation center solaris
national synchrotron radiation labora
national synchrotron radiation research center
rayonement synchrotron pour la recherche biomedicale
saga kyushu synchrotron light research center
sesame synchrotron
shanghai synchrotron radiation facility
solaris national synchrotron radiation center
soleil synchrotron
stanford synchrotron radiation labora
stanford synchrotron radiation lightsource
synchrotron light experimental science aplications midle east
synchrotron light research instit
synchrotron radiation biomedicine
synchrotron soleil

In [4]:
len('50|doi_________::')

17

In [19]:
run_affro("Information Management Systems Institute of Athena Research Centre, Greece")

[]

In [3]:
run_affro("Department of Medical and Surgical Sciences, UOC Gastroenterologia, Fondazione Policlinico Universitario A. Gemelli IRCCS, 00168 Rome, Italy")

[]

In [18]:
import requests

doi = "10.5281/zenodo.19887594"

r = requests.get(
    "https://zenodo.org/api/records",
    params={"q": f'doi:"{doi}"'}
)

r.raise_for_status()

hits = r.json()["hits"]["hits"]

if hits:
    metadata = hits[0]
    print(metadata["metadata"]["title"])

Inside LockBit: Technical, Behavioral, and Financial Anatomy of a Ransomware Empire

In [17]:
run_affro("Athena Research Center, Marousi, Greece")

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/0576by029',
  'name': 'Athena Research and Innovation Center In Information Communication & Knowledge Technologies',
  'confidence': 1.0,
  'status': 'active',
  'country': ['greece']}]

In [14]:
clean_string(". IBM Research - Almaden, San Jose, CA, USA")

'. ibm research - almaden, san jose, ca, usa'

In [5]:
run_affro("department of Business Administration, TEI of Western Macedonia, 51100 Grevena, Greece")

[]

In [20]:
run_affro("Athena Research Centre, Greece")

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/0576by029',
  'name': 'Athena Research and Innovation Center In Information Communication & Knowledge Technologies',
  'confidence': 1.0,
  'status': 'active',
  'country': ['greece']}]

In [3]:
run_affro("545 Department of Life Sciences, School of Sciences, European University, Nicosia, Cyprus.")

[{'provenance': 'affro_direct',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/04xp48827',
  'name': 'European University Cyprus',
  'confidence': 1,
  'status': 'active',
  'country': ['cyprus']}]

In [3]:
test = pd.read_json("/Users/myrto/Documents/openAIRE/github/matching/cy_sample.json", lines = True)

In [4]:
test['affro'] = [run_affro(x) for x in test['affiliation']]

In [5]:
for i in range(len(test)):
    if test['cluster_id'].iloc[i] not in str(test['affro'].iloc[i]):
        print(i, test['affiliation'].iloc[i])
        print(test['affro'].iloc[i])
        print(test['cluster_id'].iloc[i])
        print('')

36 Department of Maritime Studies, Frederick University Cyprus, 7, Y. Frederickou Str. Pallouriotisa, 1036, Nicosia, Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05d8tf882', 'name': 'Frederick University', 'confidence': 1.0, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/02qjrjx09

41 Hellenic Open University

Open University of Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/033sm2k57', 'name': 'Open University of Cyprus', 'confidence': 1.0, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/02qjrjx09

71 Middle East Technical University Northern Cyprus Campus Turkey Cyprus, Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/014weej12', 'name': 'Middle East Technical University', 'confidence': 0.7559289460184544, 'status': 'active', 'country': ['turkey']}]
https://ror.org/05qt8tf94

139 Faculty of Engineering Girne American University North Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/026b8w395', 'name': 'Girne American University', 'confidence': 0.7071067811865477, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/01pk67a30

220 KIOS CoE University of Cyprus Nicosia, Nicosia, Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02qjrjx09', 'name': 'University of Cyprus', 'confidence': 0.6324555320336758, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/04v18t651

244 Institute of Neurology & Genetics, The Cyprus School of Molecular Medicine, Nicosia, Cyprus
[]
https://ror.org/01ggsp920

288 Eratosthenes Centre of Excellence, Environment & Climate Department, Limassol, Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/03fh6pa75', 'name': 'ERATOSTHENES Centre of Excellence', 'confidence': 1.0, 'status': 'active', 'country': ['cyprus']}]
openorgs____::0000103022

308 Department of Medical Genetics, Faculty of Medicine, Cyprus Health and Social Sciences University, Morphou, Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05cv8rb65', 'name': 'Kıbrıs Sağlık ve Toplum Bilimleri Üniversitesi', 'confidence': 1.0, 'status': 'active', 'country': ['turkey']}]
https://ror.org/01gn73t32

321 Faculty of Pure and Applied Sciences, Open University of Cyprus, Latsia, Nicosia, Cyprus Faculty of Pure and Applied Sciences, Open University of Cyprus Latsia, Nicosia Cyprus.Herpetological Society of Cyprus, Paphos, Cyprus Herpetological Society of Cyprus Paphos Cyprus.
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/033sm2k57', 'name': 'Open University of Cyprus', 'confidence': 1.0, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/02qjrjx09

391 YakÄ±n Dogu University Faculty of Medicine, Department of Infectious Diseases and Clinical Microbiology, Nicosia, TRNC
[]
https://ror.org/02x8svs93

412 Cyprus Health and Social Sciences University, Faculty of Medicine, Department of Medical Microbiology, Morphou, Cyprus.
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05cv8rb65', 'name': 'Kıbrıs Sağlık ve Toplum Bilimleri Üniversitesi', 'confidence': 1.0, 'status': 'active', 'country': ['turkey']}]
https://ror.org/01gn73t32

513 Sustainable Environment and Energy Systems (SEES) Graduate Program, Middle East Technical University Northern Cyprus Campus, Kalkanli, Guzelyurt, 99738, North Cyprus, Mersin 10, Turkey
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/014weej12', 'name': 'Middle East Technical University', 'confidence': 0.7559289460184544, 'status': 'active', 'country': ['turkey']}]
https://ror.org/05qt8tf94

567 Department of Basic Sciences and Humanities Faculty of Arts and Sciences Cyprus International University, North Nicosia Northern Cyprus via Mersin  Nicosia Turkey
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/04mk5mk38', 'name': 'Cyprus International University', 'confidence': 0.8660254037844388, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/01jz1cr68

665 Dr. O. Naqshbandi (Omar Naqshbandi) is a Lecturer in Hawler Medical University. He has been completed Bachelor’s degree in Computer Engineering from Near East University- North Cyprus, and   Master’s degree in Computer Networks Principles and Practice, Hertfordshire University, London - Hertfordshire, UK. Currently, he is PhD candidate in Management Information System majoring in e- Government Information Systems, Cloud computing in Cyprus International University faculty of Sciences & information technology. Address: Erbil-Kurdistan Region-Iraq.
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/0267vjk41', 'name': 'University of Hertfordshire', 'confidence': 0.9999999999999998, 'status': 'active', 'country': ['united kingdom']}, {'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02a6g3h39', 'name': 'Hawler Medical University', 'confidence': 0.6546536707079772, 'status': 'active', 'country': ['iraq']}]
https://ror.org/02x8svs93

680 Institue of Neurology and Genetics, Nicosia, Cyprus
[]
https://ror.org/01ggsp920

686 Cyprus Near East University, Nicosia, Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02x8svs93', 'name': 'Near East University', 'confidence': 0.8660254037844388, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/02qjrjx09

703 Cyprus University of Tech-nology/Electrical Engineering, Limassol, Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02qjrjx09', 'name': 'University of Cyprus', 'confidence': 0.7071067811865475, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/05qt8tf94

737 Department of Psychology University of Cyprus Nicosia CY
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02qjrjx09', 'name': 'University of Cyprus', 'confidence': 0.5773502691896258, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/04v18t651

795 Girne American University
North Cyprus, Turkey
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/026b8w395', 'name': 'Girne American University', 'confidence': 1.0, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/01pk67a30

825 Department of Restorative Dentistry, Faculty of Dentistry, Cyprus Health and Social Sciences University, Morphou, Cyprus; Oral Microbiology and Biomaterials Laboratory, Department of Biomedical, Surgical and Dental Sciences, University of Milan, Milan, Italy.
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05cv8rb65', 'name': 'Kıbrıs Sağlık ve Toplum Bilimleri Üniversitesi', 'confidence': 1.0, 'status': 'active', 'country': ['turkey']}, {'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/00wjc7c48', 'name': 'University of Milan', 'confidence': 1.0, 'status': 'active', 'country': ['italy']}]
https://ror.org/01gn73t32

849 School of Pharmacy University of Otago  18 Frederick Street Dunedin 9054 New Zealand
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/01jmxt844', 'name': 'University of Otago', 'confidence': 0.4714045207910316, 'status': 'active', 'country': ['new zealand']}]
https://ror.org/05d8tf882

917 School of Chemistry, College of Science, University of Tehran Tehran 14176 Iran.Climate and Atmospheric Research Centre, The Cyprus Institute 20, Konstantinou Kavafi Street Nicosia 2121 Cyprus.
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05vf56z40', 'name': 'University of Tehran', 'confidence': 0.8660254037844388, 'status': 'active', 'country': ['iran']}]
https://ror.org/01q8k8p90

946 ECE Department’ Univ. of Nicosia, Radio and Telecommunications Lab, Cyprus
[]
https://ror.org/04v18t651

998 SHSO Limassol and Paphos General Hospital, Associate Educator Nursing Education Sector Cyprus Ministry of Health and University of Nicosia, Milano, Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/0032cnc36', 'name': 'Paphos General Hospital', 'confidence': 0.7071067811865475, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/02qjrjx09

1010 Department of Biochemistry, Faculty of Medicine Girne American University  Kyrenia Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/026b8w395', 'name': 'Girne American University', 'confidence': 0.7071067811865477, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/01pk67a30

1078 Department of Education Sciences, School of Humanities, Social and Education Sciences European University Cyprus Nicosia Cyprus
[{'provenance': 'affro_direct', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/04xp48827', 'name': 'European University Cyprus', 'confidence': 1, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/01jz1cr68

1250 Cyprus Health and Social Science University , Cyprus;
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05cv8rb65', 'name': 'Kıbrıs Sağlık ve Toplum Bilimleri Üniversitesi', 'confidence': 1.0, 'status': 'active', 'country': ['turkey']}]
https://ror.org/01gn73t32

1251 Cyprus Health and Social Sciences University, School of Physical Education and Sports, Guzelyurt, Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05cv8rb65', 'name': 'Kıbrıs Sağlık ve Toplum Bilimleri Üniversitesi', 'confidence': 1.0, 'status': 'active', 'country': ['turkey']}]
https://ror.org/01gn73t32

1262 Department of Electrical and Electronics Engineering, Middle East Technical University Northern Cyprus Campus, Guzelyurt, Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/014weej12', 'name': 'Middle East Technical University', 'confidence': 0.7559289460184544, 'status': 'active', 'country': ['turkey']}]
https://ror.org/05qt8tf94

1304 Frederick Research Center (FRC) and Frederick University, 1036 Nicosia, Cyprus.
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'openorgs', 'value': 'openorgs____::0000103018', 'name': 'FREDERICK RESEARCH CENTER', 'confidence': 0.8728715609439696, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/05d8tf882

1477 Cyprus Health and Social Sciences University, Guzelyurt, Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05cv8rb65', 'name': 'Kıbrıs Sağlık ve Toplum Bilimleri Üniversitesi', 'confidence': 1.0, 'status': 'active', 'country': ['turkey']}]
https://ror.org/01gn73t32

1581 Vascular Screening and Diagnostic Centre and Univ. of Nicosia Medical School, Cyprus.
[]
https://ror.org/04v18t651

1624 Open University of Cyprus & Nelson Mandela University, South Africa
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/03r1jm528', 'name': 'Nelson Mandela University', 'confidence': 0.8660254037844388, 'status': 'active', 'country': ['south africa']}]
https://ror.org/033sm2k57

1757 Cyprus Institute of Neurology, Cyprus.
[]
https://ror.org/01ggsp920

1792 Faculty of Engineering Girne American University North Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/026b8w395', 'name': 'Girne American University', 'confidence': 0.7071067811865477, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/01pk67a30

1803 Near East University, Vocational School of Health Services, Nicosia, T.R.N.C. emrahhhg@hotmail.co.uk.
[]
https://ror.org/02x8svs93

1810 Research and Education of Child Health Institute, Strovolos, Cyprus and
[]
openorgs____::0000103030

1833 Department of Physics, Mediterranean University, G. Magusa, Mersin 10, north Cyprus, Turkey
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/039ce0m20', 'name': 'Hellenic Mediterranean University', 'confidence': 0.816496580927726, 'status': 'active', 'country': ['greece']}]
https://ror.org/00excyz84

1868 Central Bank of Cyprus and Frederick University, Nicosia, Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05d8tf882', 'name': 'Frederick University', 'confidence': 0.7071067811865475, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/02qjrjx09

1902 Department of Biological Sciences - UCY - University of Cyprus [Nicosia]
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02qjrjx09', 'name': 'University of Cyprus', 'confidence': 0.816496580927726, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/04v18t651

1916 ERATOSTHENES Centre of Excellence, 3012, Limassol 3036, Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/03fh6pa75', 'name': 'ERATOSTHENES Centre of Excellence', 'confidence': 1.0, 'status': 'active', 'country': ['cyprus']}]
openorgs____::0000103022

1936 Department of Environment and Climate, Eratosthenes Center of Excelence, Limassol, Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/03fh6pa75', 'name': 'ERATOSTHENES Centre of Excellence', 'confidence': 1.0, 'status': 'active', 'country': ['cyprus']}]
openorgs____::0000103022

1951 Department of Internal Medicine Nicosia General Hospital University of Cyprus Nicosia Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02qjrjx09', 'name': 'University of Cyprus', 'confidence': 0.6396021490668312, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/04v18t651

1964 Department of Biological Sciences University of Cyprus  PO Box 20537 Nicosia 1678 Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02qjrjx09', 'name': 'University of Cyprus', 'confidence': 0.6396021490668312, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/01jz1cr68

2255 The Cyprus Institute, Nicosia, Cyprus.University of the Aegean, Mytilene, Lesvos Greece.
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/03zsp3p94', 'name': 'University of the Aegean', 'confidence': 0.816496580927726, 'status': 'active', 'country': ['greece']}, {'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/01q8k8p90', 'name': 'Cyprus Institute', 'confidence': 1.0, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/02qjrjx09

2264 Department of Computer Science University of Cyprus Nicosia 1678 Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02qjrjx09', 'name': 'University of Cyprus', 'confidence': 0.7071067811865475, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/01jz1cr68

2428 Department of Biological Sciences University of Cyprus Nicosia 1678 Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02qjrjx09', 'name': 'University of Cyprus', 'confidence': 0.7071067811865475, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/01jz1cr68

2461 Near East University, DESAM Research Institute, Nicosia, 99138, Cyprus.Near East University, Department of Medical Microbiology and Clinical Microbiology, Nicosia, 99138, Cyprus.Kyrenia University, Department of Medical Microbiology and Clinical Microbiology, Kyrenia, 99320, Cyprus.
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02x8svs93', 'name': 'Near East University', 'confidence': 1.0, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/02qjrjx09

2463 Program on Non-Profit Organizations at Yak University
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/00560h931', 'name': 'Tio Business School', 'confidence': 0.5, 'status': 'active', 'country': ['netherlands']}]
https://ror.org/02x8svs93

2492 Department of Biological Sciences University of Cyprus PO Box 20537 Nicosia 1678 Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02qjrjx09', 'name': 'University of Cyprus', 'confidence': 0.6396021490668312, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/01jz1cr68

2503 Department of Resilient Society, ERATOSTHENES Centre of Excellence, Limassol, Cyprus. constantinos.panagiotou@eratosthenes.org.cy.
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/03fh6pa75', 'name': 'ERATOSTHENES Centre of Excellence', 'confidence': 1.0, 'status': 'active', 'country': ['cyprus']}]
openorgs____::0000103022

2517 Eastern Mediterranean University  North Cyprus Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/00excyz84', 'name': 'Eastern Mediterranean University', 'confidence': 0.6123724356957945, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/02qjrjx09

2524 Department of Computer Science and Engineering, Frederick University Cyprus, Nicosia, Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05d8tf882', 'name': 'Frederick University', 'confidence': 1.0, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/02qjrjx09

2624 Akdeniz Universitycıbadem University
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/01m59r132', 'name': 'Akdeniz University', 'confidence': 0.9486832980505137, 'status': 'active', 'country': ['turkey']}]
https://ror.org/040knvs26

2658 CyRIC-Cyprus Research and Innovation Center Ltd., Nicosia, Cyprus,
[]
https://ror.org/01ha10g31

2663 Paediatric Department, Larnaca General Hospital, Larnaca European University Medical School  Nicosia Cyprus
[{'provenance': 'affro_direct', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/04xp48827', 'name': 'European University Cyprus', 'confidence': 1, 'status': 'active', 'country': ['cyprus']}, {'provenance': 'affro', 'version': '3.3.3', 'pid': 'openorgs', 'value': 'openorgs____::0000103028', 'name': 'Larnaca General Hospital', 'confidence': 0.816496580927726, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/04v18t651

2798 Dept.of Comp. Science, CY University, Nicosia, Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/04c152q53', 'name': 'İzmir Demokrasi Üniversitesi', 'confidence': 0.5773502691896258, 'status': 'active', 'country': ['turkey']}]
https://ror.org/02p65sy36

3080 Department of Computer Science, Frederick University Cyprus, Limassol, Cyprus.
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05d8tf882', 'name': 'Frederick University', 'confidence': 1.0, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/02qjrjx09

3148 Cyprus Health and Social Sciences University, Faculty of Medicine, Department of Cardiology, Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05cv8rb65', 'name': 'Kıbrıs Sağlık ve Toplum Bilimleri Üniversitesi', 'confidence': 1.0, 'status': 'active', 'country': ['turkey']}]
https://ror.org/01gn73t32

3160 Department of Political Science University of Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/02qjrjx09', 'name': 'University of Cyprus', 'confidence': 0.6324555320336758, 'status': 'active', 'country': ['cyprus']}]
https://ror.org/01jz1cr68

3186 University of Technology, Department of Agricultural Sciences, Biotechnology and Food Science Limassol, P.O Box 50329, Cyprus
[{'provenance': 'affro', 'version': '3.3.3', 'pid': 'ror', 'value': 'https://ror.org/05s32j989', 'name': 'Sivas Bilim ve Teknoloji Üniversitesi', 'confidence': 0.7071067811865475, 'status': 'active', 'country': ['turkey']}]
https://ror.org/05qt8tf94


In [15]:
run_affro(" National Research Council,National Aeronautics and Space Administration Resident Research Associate, italy")

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/04zaypm56',
  'name': 'National Research Council',
  'confidence': 1.0,
  'status': 'active',
  'country': ['italy']}]

In [14]:
run_affro("Department of Life Sciences, Program in Biological Sciences, European University Cyprus")

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/04xp48827',
  'name': 'European University Cyprus',
  'confidence': 1.0,
  'status': 'active',
  'country': ['cyprus']}]

In [15]:
run_affro("University Roma Tre. Italy")

[]

In [16]:
run_affro("CNR-IRPI, Perugia")

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/04zaypm56',
  'name': 'National Research Council',
  'confidence': 1.0,
  'status': 'active',
  'country': ['italy']}]

In [17]:
run_affro("Department of Computer Sciences and Numerical Analysis, Universidad de Co ́rdova, Cor ́doba, Spain")

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/05yc77b46',
  'name': 'University of Córdoba',
  'confidence': 0.7071067811865475,
  'status': 'active',
  'country': ['spain']}]

In [18]:
run_affro("Hospital Universitario Reina Sofía de Córdoba")

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/02vtd2q19',
  'name': 'Hospital Universitario Reina Sofía',
  'confidence': 0.8944271909999159,
  'status': 'active',
  'country': ['spain']}]

In [19]:
run_affro("Department of Earth and Atmospheric Sciences Purdue Universi 旬, West Lafayette, IN 4790 吭 U.S.A")

[]

In [6]:
run_affro("Foundation for Research and Technology Hellas—Institute of Chemical Engineering and High Temperature Chemical Processes , Stadiou Street, Platani, 26504 Patras, Greece and Department of Chemical Engineering, , 26504 Patras, Greece")

[]

In [20]:
run_affro("NHS Forth Valley, Stirling, Scotland")

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/02cme9q04',
  'name': 'NHS Forth Valley',
  'confidence': 1.0,
  'status': 'active',
  'country': ['united kingdom']}]

In [21]:
run_affro("-Ps-Graduando do Departamento de Biomecnica, Medicina e Reabilitao do Aparelho Locomotor do Hospital das Clnicas da Faculdade de Medicina de Ribeiro Preto -USP -Ribeiro Preto, SP, Brasil")

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/036rp1748',
  'name': 'Universidade de São Paulo',
  'confidence': 1.0,
  'status': 'active',
  'country': ['brazil']}]

In [8]:
dix_name['usp']

NameError: name 'dix_name' is not defined

In [22]:
run_affro(" National Research Council,National Aeronautics and Space Administration Resident Research Associate")

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/035rrps97',
  'name': 'National Research Council',
  'confidence': 1.0,
  'status': 'active',
  'country': ['romania']}]

In [23]:
run_affro("Łukasiewicz Research Network-Institute of Ceramics and Building Materials, Ceramic and Concrete Division in Warsaw, Ceramic Technology Research Group, Cementowa 8, 31-983 Kraków, Poland")

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/036f4sz05',
  'name': 'Łukasiewicz Research Network',
  'confidence': 1.0,
  'status': 'active',
  'country': ['poland']},
 {'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/05dmdhx59',
  'name': 'Institute of Ceramics and Building Materials',
  'confidence': 1.0,
  'status': 'active',
  'country': ['poland']}]

In [4]:
run_affro(',Institut für Organische Chemie,, Clausthal-Zellerfeld, Deutschland,  tu Clausthal')

[{'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/04qb8nc58',
  'name': 'Clausthal University of Technology',
  'confidence': 1.0,
  'status': 'active',
  'country': ['germany']}]

In [2]:
sample_all = pd.read_csv("/Users/myrto/Documents/openAIRE/github/matching/aff/affiliation-matching/itcygrit tests - sample_test.csv")

In [3]:
run_affro("Center for Life Nano Science @ La Sapienza, Italian Institute of Technology, Viale Regina Elena 295, 00161 Roma, Italy.Istituto Applicazioni del Calcolo, National Research Council of Italy, Via dei Taurini 19, 00185 Roma, Italy.")

[{'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/042t93s57',
  'name': 'Italian Institute of Technology',
  'confidence': 1.0,
  'status': 'active',
  'country': ['italy']},
 {'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/04zaypm56',
  'name': 'National Research Council',
  'confidence': 0.8660254037844388,
  'status': 'active',
  'country': ['italy']}]

In [4]:
for  x in sample_all['affiliation'].to_list():
    if 'affro_direct' in str(run_affro(x)):
        print(x)

Institute of Molecular Biology and Biotechnology, Foundation for Research and Technology - Hellas, Heraklion, GR-70013,, Crete, Greece. lionaki@imbb.forth.gr.
Water Research Institute, National Research Council, Verbania Pallanza, Italy

In [5]:
run_affro("intercolege, asf cyprus ")

[{'provenance': 'affro_direct',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/012gfrj24',
  'name': 'Intercollege',
  'status': 'active',
  'country': ['cyprus']}]

In [6]:
run_affro("Department of Cardiology, University General Hospital, Voutes, 71110, Heraklion, Crete, Greece")

[{'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/0312m2266',
  'name': 'University Hospital of Heraklion',
  'confidence': 0.816496580927726,
  'status': 'active',
  'country': ['greece']}]

In [7]:
run_affro("Department of Oncology, General and University Hospital, Udine; Department of Oncology, San Bortolo General Hospital, Azienda ULSS8 Berica, Vicenza.")

[{'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/05ht0mh31',
  'name': 'University of Udine',
  'confidence': 0.816496580927726,
  'status': 'active',
  'country': ['italy']}]

In [8]:
run_affro("University of Milan-Bicocca, Monza, Italy")

[{'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/01ynf4891',
  'name': 'University of Milano-Bicocca',
  'confidence': 1.0,
  'status': 'active',
  'country': ['italy']}]

In [9]:
run_affro(" ATTIKO General University Hospital")

[{'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/03gb7n667',
  'name': 'University General Hospital Attikon',
  'confidence': 0.816496580927726,
  'status': 'active',
  'country': ['greece']}]

In [10]:
run_affro(" 'York University',")

[]

In [12]:
run_affro("national research council")

[]

In [13]:
run_affro("Antalya Bilim University,Middle East Technical University North Cyprus Campus")

[{'provenance': 'affro',
  'version': '3.3.2',
  'pid': 'ror',
  'value': 'https://ror.org/014weej12',
  'name': 'Middle East Technical University',
  'confidence': 0.7559289460184544,
  'status': 'active',
  'country': ['turkey']},
 {'provenance': 'affro',
  'version': '3.3.2',
  'pid': 'ror',
  'value': 'https://ror.org/013sqra93',
  'name': 'Antalya Bilim University',
  'confidence': 1.0,
  'status': 'active',
  'country': ['turkey']}]

In [14]:
run_affro('Nursing Department Frederick University  Nicosia Cyprus')

[{'provenance': 'affro',
  'version': '3.3.2',
  'pid': 'ror',
  'value': 'https://ror.org/04v18t651',
  'name': 'University of Nicosia',
  'confidence': 0.5773502691896258,
  'status': 'active',
  'country': ['cyprus']}]

In [16]:
 run_affro("German National Research Center for Information Technology (GMD), Institute for Algorithms and Scientific Computing (SCAI), Schloß Birlinghoven, 53754 Sankt Augustin, Germany")

[{'provenance': 'affro',
  'version': '3.3.2',
  'pid': 'ror',
  'value': 'https://ror.org/00trw9c49',
  'name': 'Fraunhofer Institute for Algorithms and Scientific Computing',
  'confidence': 1.0,
  'status': 'active',
  'country': ['germany']}]

In [15]:
run_affro("Saint Luke's Hospital , Dublin 6, Ireland")

[{'provenance': 'affro',
  'version': '3.3.2',
  'pid': 'ror',
  'value': 'https://ror.org/05p668j08',
  'name': "St. Luke's General Hospital",
  'confidence': 1.0,
  'status': 'active',
  'country': ['ireland']}]

In [19]:
run_affro("Biomedical Center Munich, Department of Physiological Genomics, LMU Munich, Martinsried, Germany,Max Planck Institute for Biological Intelligence, Martinsried, Germany.")

[{'provenance': 'affro_direct',
  'version': '3.3.2',
  'pid': 'ror',
  'value': 'https://ror.org/03g267s60',
  'name': 'Max Planck Institute for Biological Intelligence',
  'confidence': 1,
  'status': 'active',
  'country': ['germany']},
 {'provenance': 'affro',
  'version': '3.3.2',
  'pid': 'ror',
  'value': 'https://ror.org/05591te55',
  'name': 'Ludwig-Maximilians-Universität München',
  'confidence': 1.0,
  'status': 'active',
  'country': ['germany']}]

In [18]:
for x in dix_name:
    if 'swansea' in x:
        print(x)

NameError: name 'dix_name' is not defined

In [2]:
run_affro("Swansea Metropolitan University")

[{'provenance': 'affro',
  'version': '3.3.2',
  'pid': 'ror',
  'value': 'https://ror.org/053fq8t95',
  'name': 'Swansea University',
  'confidence': 1,
  'status': 'active',
  'country': ['united kingdom']}]

In [16]:
run_affro("Environmental Research Laboratory, Institute of Nuclear & Radiological Sciences & Technology, Energy & Safety, National Centre for Scientific Research “Demokritos”, 15310 Ag. Paraskevi, Athens, Attica, Greece")

[{'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/038jp4m40',
  'name': 'National Centre of Scientific Research "Demokritos"',
  'confidence': 1.0,
  'status': 'active',
  'country': ['greece']}]

In [17]:
run_affro(") PhD Student, Ss. Cyril and Methodius University in Skopje, Institute of Earthquake Engineering and Engineering Seismology, Skopje, Republic of North Macedonia,")

[{'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/02wk2vx54',
  'name': 'Ss. Cyril and Methodius University in Skopje',
  'confidence': 1.0,
  'status': 'active',
  'country': ['north macedonia']}]

In [18]:
run_affro("Dermatology Department, Ifo-San Gallicano Institute, Via Chianesi 53, 00144 Roma, Italy.")

[]

In [19]:
run_affro("universita' di atene")

[{'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/04gnjpq42',
  'name': 'National and Kapodistrian University of Athens',
  'confidence': 1.0,
  'status': 'active',
  'country': ['greece']}]

In [20]:
type(run_affro( 'Stony Brook University Health Sciences Center')[0]['country'])

list

In [3]:
matchings_affro('Stony Brook University Health Sciences Center')

[('affro',
  '3.3.0',
  'ror',
  'https://ror.org/05qghxh33',
  'Stony Brook University',
  0.7071067811865477,
  'active',
  ['united states'])]

In [9]:
dix_id['https://ror.org/025h1m602']

NameError: name 'dix_id' is not defined

In [4]:
run_affro("Department of Animal Science and Technology, Konkuk University, Seoul, South Korea")

[{'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/025h1m602',
  'name': 'Konkuk University',
  'confidence': 1.0,
  'status': 'active',
  'country': ['south korea']}]

In [ ]:
sample_df = pd.read_json('/Users/myrto/Documents/openAIRE/github/matching/it_sample.json', lines = True)
print(len(sample_df))
sample_df['affro'] = [run_affro(x) for x in sample_df['affiliation'].to_list()]
sample_df['affro_ror'] = [[x['value'] for x in sample_df['affro'].iloc[i]] for i in range(len(sample_df))]
sample_df['len_affro'] = [len(x) for x in sample_df['affro_ror'].to_list()]

# {'precision': np.float64(0.6867761524175205),

35200

In [3]:
sample_df[sample_df['len_affro']>0]

,affiliation,cluster_id,affro,affro_ror,len_affro
0,Brain investigation and Neuromodulation Labora...,https://ror.org/01tevnk56,"[{'provenance': 'affro', 'version': '3.2.5', '...",[https://ror.org/01tevnk56],1
1,"Department of Chemistry, Sapienza University o...",https://ror.org/02be6w209,"[{'provenance': 'affro', 'version': '3.2.5', '...",[https://ror.org/02be6w209],1
2,"Department of Enterprise Engineering, Universi...",https://ror.org/02p77k626,"[{'provenance': 'affro', 'version': '3.2.5', '...",[https://ror.org/02p77k626],1
3,"Department of Medicine, Surgery and Dentistry ...",https://ror.org/0192m2k53,"[{'provenance': 'affro', 'version': '3.2.5', '...",[https://ror.org/0192m2k53],1
4,"Dermatology Unit, Bambino Gesù Children's Hosp...",https://ror.org/04tfzc498,"[{'provenance': 'affro', 'version': '3.2.5', '...","[https://ror.org/02sy42d13, https://ror.org/04...",2
...,...,...,...,...,...
35195,"Institute of Microbiology, University of Rome ...",https://ror.org/02be6w209,"[{'provenance': 'affro', 'version': '3.2.5', '...",[https://ror.org/02be6w209],1
35196,"Department of Nanomedicine, Houston Methodist ...",https://ror.org/00bgk9508,"[{'provenance': 'affro', 'version': '3.2.5', '...",[https://ror.org/00bgk9508],1
35197,"Department of Psychological, Pedagogical, Exer...",https://ror.org/044k9ta02,"[{'provenance': 'affro', 'version': '3.2.5', '...",[https://ror.org/044k9ta02],1
35198,"Dipartimento di Fisica, Università degli studi...",https://ror.org/05vf0dg29,"[{'provenance': 'affro', 'version': '3.2.5', '...",[https://ror.org/05vf0dg29],1
35199,"Dipartimento di Patologia Vegetale, University...",https://ror.org/027ynra39,"[{'provenance': 'affro', 'version': '3.2.5', '...",[https://ror.org/027ynra39],1

In [4]:
country = 'italy'
not_c = []
no_c =0
has_country_df = []
has_country_str_df = []

for  i in range(len(sample_df)):
    if country in sample_df['affiliation'].iloc[i].lower():
        has_country_str = True
    else:
        has_country_str = False
 
    
    has_country = False
    
    for x in sample_df['affro'].iloc[i]:
        if country in [y.lower() for y in x['country']]:
            has_country = True
            
            break
    if not has_country:
        no_c = no_c + 1   
        #print(sample_df['affiliation'].iloc[i])
        not_c.append(i)
    has_country_df.append(has_country)
    has_country_str_df.append(has_country_str)
            
sample_df['has_country'] = has_country_df
sample_df['has_country_str'] = has_country_str_df
not_country = sample_df.iloc[not_c].reset_index(drop=True)

In [5]:
len(sample_df[sample_df['has_country'] == True])

34887

In [6]:
len(sample_df) - len(sample_df[sample_df['has_country'] == True])

313

In [11]:
not_country[not_country['cluster_id'] == 'https://ror.org/02vr0ne26']

,affiliation,cluster_id,affro,affro_ror,len_affro,has_country,has_country_str
0,"Division of Radiotherapy, European Institute o...",https://ror.org/02vr0ne26,[],[],0,False,True
2,"Laboratory of Hematology-Oncology, European In...",https://ror.org/02vr0ne26,[],[],0,False,True
3,"European Institute of Oncology (IEO) IRCCS, Mi...",https://ror.org/02vr0ne26,[],[],0,False,True
8,"Cardioncology Unit, European Institute of Onco...",https://ror.org/02vr0ne26,[],[],0,False,True
11,"Molecular Medicine Program, European Institute...",https://ror.org/02vr0ne26,[],[],0,False,True
...,...,...,...,...,...,...,...
295,"Division of Pathology and Laboratory Medicine,...",https://ror.org/02vr0ne26,[],[],0,False,True
299,"Istituto Europeo di Oncologia IRCCS, Italy",https://ror.org/02vr0ne26,[],[],0,False,True
302,"European Institute of Oncology, via Ripamonti ...",https://ror.org/02vr0ne26,[],[],0,False,True
303,"Urology Department, European Institute of Onco...",https://ror.org/02vr0ne26,[],[],0,False,True
306,"Scientific Direction, European Institute of On...",https://ror.org/02vr0ne26,[],[],0,False,True

In [10]:
not_country.groupby('cluster_id').size().sort_values(ascending=False)[0:10]

cluster_id
https://ror.org/02vr0ne26    108
https://ror.org/0031wrj91     34
https://ror.org/02n2bgz18     10
https://ror.org/0240rwx68     10
https://ror.org/04x48z588      9
https://ror.org/05rbx8m02      9
https://ror.org/02g30pd64      7
https://ror.org/01xt1w755      6
https://ror.org/05aspc753      5
https://ror.org/04tfzc498      3
dtype: int64

In [67]:
not_country.groupby('cluster_id').size().sort_values(ascending=False)[40:50]

cluster_id
https://ror.org/036v5qv16    3
https://ror.org/0069akp70    3
https://ror.org/03cx6bg69    3
https://ror.org/01mymm084    3
https://ror.org/01zy69h55    2
https://ror.org/056ddyv20    2
https://ror.org/022j9ve58    2
https://ror.org/05vzagq31    2
https://ror.org/02a3mhk13    2
https://ror.org/021nszj63    2
dtype: int64

In [20]:
run_affro(" 'University of Cantabria\r\nUniversity of Limerick']")

[{'provenance': 'affro',
  'version': '3.2.5',
  'pid': 'ror',
  'value': 'https://ror.org/046ffzj20',
  'name': 'Universidad de Cantabria',
  'confidence': 0.8660254037844388,
  'status': 'active',
  'country': ['spain']}]

In [13]:
not_country[not_country['cluster_id'] == 'https://ror.org/02vr0ne26']['affiliation'].to_list()

['Division of Radiotherapy, European Institute of Oncology, Milan, Italy. Electronic address: andrea.vavassori@ieo.it.',
 'Laboratory of Hematology-Oncology, European Institute of Oncology, Via Ripamonti 435, 20141, Milan, Italy. francesco.bertolini@ieo.it.',
 'European Institute of Oncology (IEO) IRCCS, Milan, Italy. livmagnhild.austenaa@ieo.it.',
 'Cardioncology Unit, European Institute of Oncology,\nMilan, Italy',
 'Molecular Medicine Program, European Institute of Oncology, Milano, Italy.',
 'Department of Obstetrics and Gynaecology, University Hospitals Leuven, 3000 Leuven, Belgium.Department of Obstetrics and Gynaecology, Jessa Hospital, 3500 Hasselt, Belgium, Email: jasper.verguts@jessazh.be.Division of Gynaecology, European Institute of Oncology, Via Ripamonti, 435, 20141 Milano, Italy. Email: angelo.maggioni@ieo.it. Email: vanna.zanagnolo@ieo.it.',
 'Department of Head and Neck Surgery and Otorhinolaryngology, IEO, European Institute of Oncology IRCCS, Milan, Italy.',
 'Department of Experimental Oncology, European Institute of Oncology, Via Ripamonti 435, I20141 Milano, Italy. alberto.donofrio@ifom-ieo-campus.it',
 'Psycho-Oncology Division, European Institute of Oncology, Milan 20141, MI, Italy',
 'Scientific Directorate, European Institute of Oncology, Milan, Italy.',
 'Division of Medical Oncology, European Institute of Oncology, Milan,',
 'Gynecologic Oncology Program, European Institute of Oncology IRCCS, Milan, Italy. fedro.peccatori@ieo.it.',
 'Library, European Institute of Oncology IRCCS, Milan, Italy.',
 'From the European Institute of Oncology; Hospital San Raffaele, Milan, Italy; Pathology Institute, Locarno; Oncology Institute of Southern Switzerland, Bellinzona, Switzerland',
 'Soft Tissue Sarcoma and Rare Tumors Surgical Division, European Institute of Oncology, Milan, Italy',
 'Department of Experimental Medicine, European Institute of Oncology (IEO), Via Adamello 16, 20139 Milan, Italy',
 'Unit of Gastrointestinal Medical Oncology and Neuroendocrine Tumors, European Institute of Oncology, IEO, Milan, Italy',
 'Division of Thoracic Surgery, European Institute of Oncology, 20141 Milan, Italy.',
 'Department of Epidemiology and Biostatistics, European Institute of Oncology, I-20141 Milan, Italy',
 'European Institute of Oncology IRCCS, Department of Experimental Oncology, Milan, Italy.',
 'European Institute of Oncology IRCCS, 20141, Milan, Italy',
 'European Institute of Oncology, Division of Otolaryngology and Head and Neck Surgery, Milan, Italy',
 'Division of Pathology, IEO, European Institute of Oncology IRCCS, 20144 Milan, Italy',
 'Drug Development Program, European Institute of Oncology, Milan, Italy; and',
 '1European Institute of Oncology IEO, Milan, MI, Italy.',
 'Gynecology Oncology Division, European Institute of Oncology, Milan, Italy.',
 'From the Division of Epidemiology and Biostatistics, European Institute of Oncology, Milano, Italy',
 'Division of Medical Oncology at the European Institute of Oncology, Milano, Italy.',
 'Division of Haemato-Oncology, European Institute of Oncology IRCCS, Viale Ripamonti, Milano, Italy',
 'Division of Cancer Prevention and Genetics, Istituto Europeo di Oncologia, Via Ripamonti 435, 20141, Milan, Italy. bernardo.bonanni@ieo.it.',
 'Melanoma and muscle-cutaneous sarcomas Division, European Institute of Oncology, Milan, Italy',
 'Applied Research Division for Cognitive and Psychological Science, European Institute of Oncology (IEO), Via Ripamonti, Milan, Italy',
 'Plastic Surgery Unit, European Institute of Oncology, Milan, Italy',
 'Department of Medicine, European Institute of Oncology, Via Ripamonti 435, 20141 Milan, Italy,',
 'Division of Experimental Therapeutics, European Institute of Oncology, Milan, Italy.',
 'Present address: Department of Experimental Oncology, European Institute of Oncology, Milan, Italy',
 'Division of Urology, European Institute of Oncology IRCCS, 20139 Milan, Italy',
 'Department of Experimental Oncology, Molecular Medicine for Care Program, European Institute of Oncology, Via Ripamonti 435, 20141 Milan, Italy.',
 'Division of Anesthesiology, European Institute of Oncology, Italy',
 'Division of Experimental Therapeutics, Istituto Europeo di Oncologia, Via Ripamonti 435, 20141 Milano, Italy.',
 'Department of Urology, European Institute of Oncology (IEO) IRCCS, 20141 Milan, Italy.',
 'Christina Fotopoulou, Imperial College London, London, United Kingdom; Jalid Sehouli, Charité Medical University of Berlin, Berlin, Germany; Giovanni Aletti, European Institute of Oncology, Milan, Italy; Philipp Harter, Kliniken Essen Mitte, Essen, Germany; Sven Mahner, Ludwig-Maximilians-University, Munich, Germany; Denis Querleu, Institut Bergonié, Bordeaux, France; Luis Chiva, Clínica Universidad de Navarra, Navarra, Spain; Hani Gabra, Imperial College London, London, United Kingdom; Nicoletta Colombo...',
 'Department of Radiation Oncology, European Institute of Oncology, Via Giuseppe Ripamonti, 435 - 20141, Milan, Italy.',
 'Division of Medical Oncology for Melanoma, Sarcoma, and Rare Tumors, European Institute of Oncology (IEO), European Istituto di Ricovero e Cura a Carattere Scientifico (IRCCS), Milano, Italy',
 'Institute of Medicine, University of Bergen, Bergen, Norway; European Institute of Oncology, Milan, Italy; Galliera Hospital, Genoa, Italy; Haukeland University Hospital, Bergen, Norway',
 'Laboratory Medicine Division, European Institute of Oncology, Milano, Italy',
 'Dipartimento di Oncologia Sperimentale, Istituto Europeo di Oncologia, Milan, Italy.',
 'Divisions of Senology, European Institute of Oncology, Milan, Italy',
 'European Institute of Oncology, Division of Epidemiology and Biostatistics, Milan, Italy.',
 'Unit of Research in Medical Senology, Department of Medicine, European Institute of Oncology, Via Ripamonti 435, 20141 Milan, Italy. laura.orlando@ieo.it',
 'IEO - Istituto Europeo di Oncologia, Milan, Italy',
 'Division of Pathology and Laboratory Medicine, European Institute of Oncology, Via Ripamonti 435, Milan, Italy',
 'Division of Thoracic Oncology, Istituto Europeo di Oncologia, Milano, Italy',
 'cDepartment of Experimental Oncology, European Institute of Oncology, 20141 Milan, Italy',
 'Department of Hematology, Istituto Europeo di Oncologia, Milan, Italy.',
 'Division of Cancer Prevention and Genetics, European Institute of Oncology IRCCS, Milan, Italy',
 'Cancer Prognostics and Health Outcomes Unit, Division of Urology, University of Montréal Health Center, Montréal, Québec, Canada.European Institute of Oncology, Milan, Italy.',
 'Medical Oncology Unit of Respiratory Tract and Sarcomas, European Institute of Oncology, Milan, Italy. tommaso.de-pas@ieo.it',
 'European Institute of Oncology, Department of Experimental Oncology, Via Ripamonti 435, I-20141 Milano, Italy',
 'European Institute of Oncology, Department of Experimental Oncology, Milan, Italy',
 'Department of Radiotherapy, European Institute of Oncology, Via Ripamonti 435, 20141, Milan, Italy. surgo.alessia@ieo.it.',
 'Unità Di Mobilizzazione e Raccolta CSE, Divisione Di Laboratorio Di Ematoncologia Clinica, Istituto Europeo Di Oncologia IRCCS- Milano, Italy.',
 'Medical Physics Department, European Institute of Oncology, Milan, Italy',
 'Unit of Sarcomas and Thymomas, European Institute of Oncology, 20136 Milan, Italy',
 'Division of Radiology, European Institute of Oncology IRCCS, 20139 Milan, Italy.',
 'IEO, European Institute of Oncology IRCCS, Unit of Radiation Research, Milan, Italy;',
 'Unità Di Mobilizzazione e Raccolta CSE, Divisione Di Laboratorio Di Ematoncologia Clinica, Istituto Europeo Di Oncologia IRCCS- Milano, Italy',
 'Department of Radiotherapy, European Institute of Oncology IRCCS, Milan, Italy',
 'European Institute of Oncology, Department of Plastic and Reconstructive Surgery, Milan, Italy',
 'Department of Experimental Oncology, Istituto Europeo di Oncologia, Milan, Italy57Cogentech Cancer Genetic Test Laboratory, Milan, Italy.',
 'Crystallography Unit, Department of Experimental Oncology, European Institute of Oncology, IFOM-IEO Campus, 20139 Milan, Italy.',
 'Head and Neck Surgery Division, European Institute of Oncology, Milan, Italy;',
 'European Institute of Oncology, Milano, Italy. roberto.gennari@ieo.it',
 'Department of Radiology, European Institute of Oncology, Via Ripamonti 435, 20141, Milan, Italy, giuseppe.petralia@ieo.it.',
 'Department of Urology, Istituto Europeo di Oncologia (IEO), Via Ripamonti 435, Milan, Italy',
 'Division of Medical Senology, Istituto Europeo di Oncologia, Milan, Italy.',
 'Epidemiology and Biostatistics, European Institute of Oncology, Milan, Italy',
 'European Institute of Oncology, Division of Nuclear Medicine, Milan, Italy. direzione.mnu@ieo.it',
 'Division of Urology, European Institute of Oncology IRCCS, 20122 Milan, Italy',
 'Department of Thoracic Surgery, IEO, European Institute of Oncology IRCCS , 20141 Milan,',
 'European Institute of Oncology, Division of Thoracic Surgery, Milano,#N#                    Italien',
 'Cancer Prognostics and Health Outcomes Unit, University of Montreal Hospital Center, Montreal, Quebec, Canada.Department of Urology, European Institute of Oncology, Milan, Italy.',
 'European Institute of Oncology, Milan, Italy',
 'Division of Pathology and Laboratory Medicine, European Institute of Oncology, Milan, Italy,',
 'Division of General and Laparoscopic Surgery, European Institute of Oncology, Via G. Ripamonti, 435, 20141, Milan, Italy',
 'Digestive Surgery, European Institute of Oncology IRCCS, Milan, Italy. Electronic address: emilio.bertani@ieo.it.',
 'Medical Oncology Division of Urogenital and Head & Neck Tumours, European Institute of Oncology, Via Ripamonti 435, 20141, Milan, Italy',
 'Division of Otolaryngology and Head and Neck Surgery, IEO, European Institute of Oncology IRCCS, Milan, Italy.',
 '6Gynecologic Oncology Division, European Institute of Oncology, Milan, Italy.',
 'Department of Oncology, Istituto Europeo di Oncologia, Milan.',
 'Division of Early Drug Development for Innovative Therapies, Istituto Europeo di Oncologia, Via Ripamonti 435, 20133 Milano, Italy',
 'Department of Medicine, Division of Medical Oncology, Day Hospital Unit, European Institute of Oncology, Via Ripamonti 435, 20141 Milan, Italy',
 'Unit of Histopathology and Molecular Diagnostics, Division of Pathology, IEO, European Institute of Oncology IRCCS, 20141 Milan, Italy. caterina.fumagalli@ieo.it.',
 '2Department of Experimental Oncology, European Institute of Oncology (IEO), 20139 Milan, Italy;',
 'European Institute of Oncology, Milano',
 'Department of Obstetrics and Gynecology, Mayo Clinic, Rochester, Minnesota, USA.Division of Gynecologic Oncology, IEO, European Institute of Oncology IRCCS, Milan, Lombardia, Italy.',
 'Division of Otolaryngology and Head and Neck Surgery, European Institute of Oncology, 20141 Milan, Italy',
 'Department of Thoracic Surgery, IRCCS European Institute of Oncology, Milan, Italy;',
 '3European Institute of Oncology (IEO), Milan, Italy',
 'Division of Gastrointestinal Medical Oncology and Neuroendocrine Tumors, European Institute of Oncology, IEO IRCCS, Via Ripamonti 435, Milan, Italy. nicola.fazio@ieo.it.',
 'New Drug Development for innovative therapies, IEO - Istituto Europeo di Oncologia IRCCS, Milan, Italy',
 'Division of Otolaryngology Head &amp; Neck Surgery, IEO, European Institute of Oncology IRCCS, 20141 Milan, Italy',
 'Radiation Oncology Department, European Institute of Oncology, Milan, Italy. annamaria.ferrari@ieo.it',
 'Division of Pathology and Laboratory Medicine,  European Institute of Oncology, Milan, Italy',
 'Istituto Europeo di Oncologia IRCCS, Italy',
 'European Institute of Oncology, via Ripamonti 435, Milan, I-20132, Italy',
 'Urology Department, European Institute of Oncology, Milan, Italy',
 'Scientific Direction, European Institute of Oncology, 20141 Milan, Italy']

In [14]:
not_country[not_country['cluster_id'] == 'https://ror.org/04h36ea57']

Empty DataFrame
Columns: [affiliation, cluster_id, affro, affro_ror, len_affro, has_country, has_country_str]
Index: []

In [10]:
run_affro(" Royal Colleges of Surgeons in Ireland, Medical University of Bahrain, Manama, Bahrain',")

[{'provenance': 'affro',
  'version': '3.3.2',
  'pid': 'ror',
  'value': 'https://ror.org/01h4bh480',
  'name': 'Royal College of Surgeons in Ireland - Bahrain',
  'confidence': 1.0,
  'status': 'active',
  'country': ['bahrain']}]

In [11]:
run_affro(" 'Personalized Medicine, Asthma and Allergy, Humanitas Clinical and Research Center, IRCCS, Rozzano.',")

[{'provenance': 'affro',
  'version': '3.3.2',
  'pid': 'ror',
  'value': 'https://ror.org/05fnzzk18',
  'name': 'Center for Clinical Research (United States)',
  'confidence': 0.8660254037844388,
  'status': 'active',
  'country': ['united states']},
 {'provenance': 'affro',
  'version': '3.3.2',
  'pid': 'ror',
  'value': 'https://ror.org/04tfzc498',
  'name': 'Istituti di Ricovero e Cura a Carattere Scientifico',
  'confidence': 1.0,
  'status': 'active',
  'country': ['italy']}]

In [ ]:
run_affro(" 'Istituto di Patologia Vegetale, Université degli Studi, Bologna, Italy',")

In [2]:
import pandas as pd
sample_df = pd.read_json('/Users/myrto/Documents/openAIRE/github/matching/it_sample.json', lines = True)
print(len(sample_df))
sample_df['affro'] = [run_affro(x) for x in sample_df['affiliation'].to_list()]
sample_df['affro_ror'] = [[x['value'] for x in sample_df['affro'].iloc[i]] for i in range(len(sample_df))]
sample_df['len_affro'] = [len(x) for x in sample_df['affro_ror'].to_list()]

35200

In [3]:
sample_df['curated'] = [[x] for x in sample_df['cluster_id'].to_list()]

In [4]:
evaluate_micro(sample_df, 'affro_ror')

{'precision': np.float64(0.7634363097757089),
 'recall': np.float64(0.97375),
 'f1_score': np.float64(0.8558622670012609)}

In [11]:
run_affro(" 'Istituto di Patologia Vegetale, Université degli Studi, Bologna, Italy',")

[{'provenance': 'affro',
  'version': '3.2.5',
  'pid': 'ror',
  'value': 'https://ror.org/039xw7n32',
  'name': 'University Institute of European Studies',
  'confidence': 0.7071067811865475,
  'status': 'active',
  'country': ['italy']}]

In [12]:
sample_df[sample_df['affiliation'] == 'Istituto di Patologia Vegetale, Université degli Studi, Bologna, Italy']

,affiliation,cluster_id,affro,affro_ror,len_affro,curated,TP_affro_ror,FP_affro_ror,FN_affro_ror
38,"Istituto di Patologia Vegetale, Université deg...",https://ror.org/03fc1k060,"[{'provenance': 'affro', 'version': '3.2.5', '...",[https://ror.org/039xw7n32],1,[https://ror.org/03fc1k060],0,1,1

In [10]:
sample_df[sample_df['FN_affro_ror']>0]['affiliation'].to_list()

['Division of Radiotherapy, European Institute of Oncology, Milan, Italy. Electronic address: andrea.vavassori@ieo.it.',
 'Istituto di Patologia Vegetale, Université degli Studi, Bologna, Italy',
 'Dipartimento di Agraria, Università degli Studi di Napoli "Federico II", via Università 100, Portici (NA), Italy.',
 'Personalized Medicine, Asthma and Allergy, Humanitas Clinical and Research Center, IRCCS, Rozzano.',
 'Department of Medical Translational Sciences & European Laboratory for the Investigation of Food-Induced Diseases, University Federico II, Naples, Italy',
 "Dipartimento di Malattie Infettive, Parassitarie ed Immunomediate, Istituto Superiore di Sanità, Viale Regina Elena 299, 00161 Rome, Italy 2Dipartimento di Medicina di Laboratorio e Microbiologia, Università Campus Biomedico, Via Emilio Longoni 83, 00155 Rome, Italy 3Dipartimento di Scienze Neurologiche, Psichiatriche e Riabilitative dell'Età Evolutiva, Università 'La Sapienza', Via dei Sabelli 108, 00185 Rome, Italy.",
 'Laboratory of Hematology-Oncology, European Institute of Oncology, Via Ripamonti 435, 20141, Milan, Italy. francesco.bertolini@ieo.it.',
 'Division of Internal Medicine, Santa Maria Nuova Hospital, 50100 Firenze, Italy.',
 "Università degli Studi dell'Insubria, Science and High Technology Department, 22100, Como, Italy. Electronic address: barbara.giussani@uninsubria.it.",
 'Department of Human Neurosciences, Sapienza, University of Rome , Rome 00185 ,',
 'European Institute of Oncology (IEO) IRCCS, Milan, Italy. livmagnhild.austenaa@ieo.it.',
 'Monash University Monash University',
 "INFN Sezione di Milano Bicocca and Dipartimento di Scienza e Alta Tecnologia, Universit degli Studi dell'Insubria Via Valleggio, 22100 Como, Italy",
 '1 Bio@SNS Laboratory of Biology, Scuola Normale Superiore, Pisa, Italy.3 Neurotrophins and Neurodegenerative Diseases Laboratory, Rita Levi-Montalcini European Brain Research Institute, Rome, Italy.',
 'European Center for Theoretical Studies in Nuclear Physics and Related Areas (ECT*) strada delle tabarelle, 286 -38123 -Villazzano (Trento), Italy.',
 'Institute for Pharmacological Research ‘Mario Negri’, Via Giuseppe La Masa 19, 20156 Milan, Italy',
 'Unit of Neurology VIII—Clinics of Central and Peripheral Degenerative Neuropathies, Department of Clinical Neurosciences, IRCCS Foundation, C Besta Neurological Institute, Milan, Italy',
 'Le Scotte Hospital, Azienda Ospedaliera Universitaria, Siena, Siena, Italy',
 'Department of Bioengineering, Politecnico di Milano University, Milan, Italy',
 'C. Cisari, MD, Department of Physical Medicine and Rehabilitation, Azienda Universitaria Ospedaliera, Maggiore della Carità, and Department of Clinical and Experimental Medicine, University of Eastern Piedmont, A. Avogadro.',
 'Cardioncology Unit, European Institute of Oncology,\nMilan, Italy',
 'Universit de Lige, facult de mdecine vtrinaire, service de nutrition animale, rue des Vtrinaires, 45, 1070 Bruxelles, Belgique',
 'Universities of Bologna and Florence.',
 'Universit de Lige, 4000 Lige, Belgique ;',
 'Molecular Medicine Program, European Institute of Oncology, Milano, Italy.',
 'Istituto Nazionale di Fisica Nucleare Trieste/Udine, I-33100 Udine, Italy and University of Trieste, I-34127 Trieste, Italy.',
 'Department of Biology, University “Federico II”, Naples, Italy',
 'Department of Obstetrics and Gynaecology, University Hospitals Leuven, 3000 Leuven, Belgium.Department of Obstetrics and Gynaecology, Jessa Hospital, 3500 Hasselt, Belgium, Email: jasper.verguts@jessazh.be.Division of Gynaecology, European Institute of Oncology, Via Ripamonti, 435, 20141 Milano, Italy. Email: angelo.maggioni@ieo.it. Email: vanna.zanagnolo@ieo.it.',
 'Department of Head and Neck Surgery and Otorhinolaryngology, IEO, European Institute of Oncology IRCCS, Milan, Italy.',
 'European Laboratory for Nonlinear Spectroscopy (LENS), Via Nello Carrara 1, 50019 Sesto Fiorentino, Italy',
 'Department of Experimental Oncology, European Institute of Oncology, Via Ripamonti 435, I20141 Milano, Italy. alberto.donofrio@ifom-ieo-campus.it',
 'Department of Clinical and Experimental Medicine, University of Parma, Ospedale Maggiore, Via Gramsci 14, Parma, 43100, Italy',
 'European Laboratory for Non-Linear Spectroscopy (LENS), University of Florence, 50019 Sesto-Fiorention, Italy',
 'Department ABC, Technical University of Milan, Milan, Italy',
 'Division of Cardiology, Department of Clinical Medicine, Cardiovascular and Immunologic Sciences, Federico II University, Naples, Italy.',
 'Division of Breast Cancer Surgery, IEO, European Institute of Oncology, IRCCS.Department of Oncology and Haemato-Oncology, University of Milan, Milan, Italy.',
 'Department of Experimental Oncology, European Institute of Oncology - IEO IRCCS, Milan, Italy; Department of Biomedical Sciences, University of Padova, Padua, Italy. Electronic address: marco.giorgio@unipd.it.',
 'Department of Urology, European Institute of Oncology, Milan, Italy.Dipartimento di Emato-Oncologia ed Oncologia, University of Milan, Milan, Italy.',
 'Fondazione Policlinico Universitario Campus Bio-Medico, Via Alvaro del Portillo, 200-00128 Roma, Italy.Research Unit of Endocrinology and Diabetology, Department of Medicine and Surgery, Università Campus Bio-Medico di Roma, Via Alvaro del Portillo, 21-00128 Roma, Italy.',
 'MS Clinical Care and Research Centre, Department of Neuroscience, "Federico II\'\' University, Naples, Italy; Queen Square MS Centre, Department of Neuroinflammation, UCL Queen Square Institute of Neurology, University College of London, UK.',
 "Dipartimento di Fisica, Università degli Studi dell' Aquila, 67010 Coppito, L'Aquila, Italy",
 'Psycho-Oncology Division, European Institute of Oncology, Milan 20141, MI, Italy',
 'Institute of structure of matter (ISM) - National Research Council (CNR)',
 'Laboratori di Biologia, Istituto Superiore di Sanita, University of Rome and «Regina Elena» Institute, Rome, Italy',
 'Department of Clinical Medicine and Surgery, Regional Reference Centre for Coagulation Disorders, Federico II University, Naples, Italy. dario.diminno@hotmail.it',
 'SC Anestesia e Rianimazione, Ospedale San Paolo - Polo Universitario, ASST Santi Paolo e Carlo, 20142 Milan, Italy. alice.veronese@unimi.it.',
 'Centro di Calcolo Elettronico, Universita’ di Cagliari, Via Universita’ 40, 09124, Cagliari, Italy',
 'Department of Medicine and Urgency, Nuclear Medicine Unit, Ospedale degli Infermi, Via dei Ponderanesi 2, Ponderano\n(BI), Italy',
 'Department of Regenerative Medicine Research, Institute of Biomedical Research and Innovation',
 'Department of Veterinary Medicine and Animal Production, Federico II University, V. F. Delpino 1, 80137 Naples, Italy. neglia@unina.it.',
 'Dipartimento di Endocrinologia e Oncologia Clinica e Molecolare, Università Federico II, Napoli, Italy',
 'European Society of Sexual Medicine',
 'Department of Rheumatology and medical sciences, ASST G. Pini-CTO, Milan and University of Milan, Milan, Italy.',
 'Sapienza, Università di Roma, Dipartimento di Psicologia, Roma, Italy; I. R. C. S. S. Fondazione Santa Lucia, Roma, Italy. Electronic address: cecilia.guariglia@uniroma1.it.',
 'Libero professionista in Milano; professore a contratto di Parodontologia, CLMOPD, presidente prof. A. Tagliabue, Università degli Studi dell’Insubria, Varese',
 'Interdepartmental Research Centre on Nuclear Magnetic Resonance (NMR) for the Environment, Agro-Food and New Materials (CERMANU), Università degli Studi di Napoli Federico II, Via Università 100, 80055 Portici, Italy.',
 'Azienda Ospedaliero-Universitaria Policlinico, Scienze Ostetriche, Ginecologiche e Pediatriche,\r\nModena, Italy',
 'Department of Pathology, European Institute of Oncology, Istituto di ricovero e cura a carattere scientifico (IRCCS), Milano, Italy.',
 'EINGE Biotecnologie Avanzate and Hematology Division, Department of Biochemistry and Medical Biotechnology, University Federico II, Naples;',
 'Telethon Institute of Genetics and Medicine (TIGEM), Pozzuoli, Naples, Italy.Medical Genetics, Department of Translational Medicine (DISMET), "Federico II" University, Naples, Italy.',
 'Scientific Directorate, European Institute of Oncology, Milan, Italy.',
 'Division of Medical Oncology, European Institute of Oncology, Milan,',
 'Gynecologic Oncology Program, European Institute of Oncology IRCCS, Milan, Italy. fedro.peccatori@ieo.it.',
 'Klinik und Poliklinik für Orthopädie der Universität zu Köln (Direktor: Universitätsprofessor Dr. med. P. Eysel)',
 'Institute of Neuroscience, Eugene, Oregon 97403',
 'Laboratory of Immunology, Institute of Pharmacological Research “Mario Negri”, Milan, Italy',
 'Library, European Institute of Oncology IRCCS, Milan, Italy.',
 'NNL, National Nanotechnology Laboratory of CNR-INFM, Università degli Studi del Salento c/o Distretto Tecnologico ISUFI, via Arnesano, I-73100 Lecce, Italy',
 'Institute of Biology and Molecular Pathology, IBPM-CNR, Rome, Italy.IRCCS San Raffaele, Rome, Italy.',
 'Nuovo Ospedale degli Infermi, Biella',
 'Section of Psychology, Department of Surgical, Medical, Molecular, and Critical Area Pathology, University of Pisa Pisa, Italy ; Department of Clinical Psychology and Pychotherapy, Babes-Bolyai University Cluj-Napoca, Romania.',
 'Department of Biomedical Sciences for Health, Functional Anatomy Research Center (FARC), Università degli Studi di Milano, Milano, Italy; Institute of Bioimaging and Molecular Physiology, National Research Council, Segrate, Italy. Electronic address: chiarella.sforza@unimi.it.',
 'European Laboratory for Non-linear Spectroscopy , via N. Carrara 1, 50019 Sesto Fiorentino Firenze, Italy',
 'Faculty of Economics, Universita degli Studi eCampus , ,',
 'National Institute of Optics CNR-INO and European Laboratory for Non Linear Spectroscopy LENS, Via Nello Carrara 1, 50019, Sesto Fiorentino, Italy',
 'Interventional Radiology, Azienda Ospedaliera Universitaria-Ospedali Riuniti di Ancona, Ancona, Italy.',
 'Dipartimento di Medicina Clinica e Chirurgia, Federico II University, Naples',
 'Rheumatology, Federico II University, Naples, Italy. rscarpa@unina.it',
 'Department of Pediatrics, Federico II University, Via Sergio Pansini 5, Naples 80131, Italy.',
 'Department of Pediatrics, Federico II University, Naples, 80131, Italy',
 'Urologi Ospedalità Gestione Privata (UrOP); Department of Urology, IEO European Institute of Oncology, IRCCS, Milan. Ottavio.DeCobelli@unimi.it.',
 'Fondazione Policlinico Universitario Campus Bio-Medico, Via Alvaro del Portillo, 200, Rome, 00128, Italy.Research Unit of Intelligent Technology for Health and Wellbeing, Department of Engineering, Università Campus Bio-Medico di Roma, Via Alvaro del Portillo, 21, Rome, 00128, Italy.',
 'c Institute of Clinical Physiology - National Research Council (IFC-CNR) , Pisa-Lecce , Italy.',
 'Multiple Sclerosis Clinical Care and Research Centre, Department of Neuroscience, Reproductive Science and Odontostomatology, Federico II University, Via Sergio Pansini, 5 – Building 17, Ground floor, Naples, Italy',
 'Treg Cell Lab, Dipartimento di Medicina Molecolare e Biotecnologie Mediche, Università degli Studi di Napoli “Federi II”, Naples, Italy',
 '* *Department of Economics and Finance, Brunel University, Uxbridge, UB8 3PH; and University of Rome Tor Vergata, CEDI and CMPO; e-mail: Elisabetta.Iossa@brunel.ac.uk',
 'European Academy Bozen/Bolzano (EURAC), Drususallee 1, 39100 Bozen, Italy',
 'Metropolitan nuclear medicine, Azienda Ospedaliera-Universitaria di Bologna S. Orsola Malpighi, Bologna, Italy',
 'From the University of California at Los Angeles (UCLA) Stroke Center (C.S.K., J.R.A., S.S., P.V., J.B., J.L.S.); the Departments of Neurology (C.S.K., S.S., J.L.S.), Radiological Sciences (J.R.A., P.V., J.B.), and Emergency Medicine (S.S.); and the UCLA Brain Research Institute, UCLA Medical Center, Los Angeles, Calif; and the Department of Radiology, First Medical Faculty, University of Naples, Italy (F. Di S.).',
 'Department of General and Environmental Physiology, Section of Microbiology, University Federico II, via Mezzocannone 16, 80134 Naples, Italy. defelice@unina.it',
 'From the European Institute of Oncology; Hospital San Raffaele, Milan, Italy; Pathology Institute, Locarno; Oncology Institute of Southern Switzerland, Bellinzona, Switzerland',
 'National Research Council, Institute for Water Research (CNR-IRSA), Monterotondo, RM, Italy',
 "Dip. di Scienza e Alta Tecnologia, Univ. degli Studi dell'Insubria, 22100 Como, Italy",
 'Polytechnic School of Basic Sciences, Federico II University, Naples, Italy',
 'EURATOM/IPP.CR Association, Institute of Plasma Physics, 182 00 Prague, Czech Republic',
 'University of Milan  Bicocca',
 'Department of Scienze e Biotecnologie Medico-Chirurgiche, University of Rome, Sapienza, Polo Pontino, Latina;',
 'Dipartimento di Ingegneria dei Materiali e della Produzione, Università Federico II, piazzale V. Tecchio 80, 80125 Napoli, Italy',
 '5San Gallicano Dermatologic Institute, Rome, Italy',
 'Prof. Dipartimento di Ingegneria Chimica, Università “Federico II”, Napoli, Italy.',
 'Soft Tissue Sarcoma and Rare Tumors Surgical Division, European Institute of Oncology, Milan, Italy',
 'c Institute of Cell Biology and Neurobiology, National Research Council (IBCN-CNR)/Santa Lucia Foundation, 00143 Rome, Italy.',
 'Veterinary Public Health Service, Local Health Authority 10, Firenze, Italy.',
 'LIUC -Universit Cattaneo, Castellanza, VA, Italy;',
 'Department of Computer Science and Automation, University Roma, Tre, Rome, Italy',
 'Department of Radiotherapy, European Institute of Oncology and University of Milan, Italy',
 'Regional Center for Special Optics and Optoelectronic Systems (TOPTEC), Institute of Plasma Physics, Czech Academy of Science v.v.i., Za Slovankou 1782/3, 182 00 Prague 8, Czech Republic',
 'Contribution from Dipartimento di Chimica, Universita Federico II, Complesso Universitario Monte S.Angelo, via Cintia, I-80126 Napoli, Italy',
 'Archaeology, College of Humanities, Arts and Social Sciences, Flinders University, Adelaide, Australia.FAPAB Research Center.Department of Humanities, University of Catania, Sicily.',
 'Institute of Endocrinology and Experimental Oncology (IEOS), National Research Council (CNR) , Naples,',
 'Department of Experimental Oncology, European Institute of Oncology IRCCS, 20139 Milano, Italy.Department of Oncology and Hematology-Oncology, University of Milan, 20122 Milano, Italy.',
 'and requests for reprints to Prof. Generoso Andria, Department of Pediatrics, Federico II University, Via Pansini 5, 80131 Naples, Italy.',
 'Division of Radiotherapy, European Institute of Oncology, University of Milan, Italy',
 'Immuno-haematology and Blood Transfusion Centre, Santa Maria Hospital, Terni, Italy',
 'Department of Experimental Medicine, European Institute of Oncology (IEO), Via Adamello 16, 20139 Milan, Italy',
 'Plant Protection Institute, Section of Bari, National Research Council, Via Amendola 122/D, 70126, Bari, Italy',
 'Hosmotic Srl, Vico Equense, Naples, Italy.Theoreo Srl, Pugliano, Salerno, Italy.Department of Medicine, Surgery and Dentistry, "Scuola Medica Salernitana", University of Salerno, Baronissi, Salerno, Italy.European Biomedical Research Institute of Salerno (EBRIS), Salerno, Italy.',
 'Private higher education institution "European University"',
 'Division of Gastrointestinal and Neuroendocrine Tumors, European Institute of Oncology, IRCCS, Milan, Italy; Molecular Medicine Program, University of Pavia, Pavia, Italy.',
 'Humanitas University and IRCCS Humanitas Research Hospital-Humanitas Cancer Center, Milan, Italy',
 'Unit of Gastrointestinal Medical Oncology and Neuroendocrine Tumors, European Institute of Oncology, IEO, Milan, Italy',
 'DISCo, University of Milan Bicocca, via Bicocca degli Arcimboldi, 8, Milan, 20135, Italy. bonizzoni@disco.unimib.it',
 'cInstitute of Clinical Physiology, National Research Council, Pisa, Italy',
 'Dipartimento di Matematica e Applicazioni “R. Caccioppoli”, Università degli Studi di Napoli, Via Mezzocannone, 8, 80134, Napoli',
 'Division of Thoracic Surgery, European Institute of Oncology, 20141 Milan, Italy.',
 'Department of Epidemiology and Biostatistics, European Institute of Oncology, I-20141 Milan, Italy',
 'Health Management, School of Medicine, Federico II University, via Sergio Pansini 5, 80131, Naples, Italy',
 'U.O. Emodinamica-Abienda, Ospedaliera Universitaria, Viale Bracci 14, 53100, Siena, Italy',
 'Division of Neurology and Neuropathology; Department of Diagnostics and Applied Technology, IRCCS Foundation, "C. Besta" Neurological Institute, Milan, Italy.',
 "\n Dipartimento di Biologia Strutturale e Funzionale, Università degli Studi dell'Insubria, Via J.H. Dunant 3, Varese, Italy",
 '8Gynecologic Cancer Program, European Institute of Oncology and University of Milan-Bicocca, Milan, Italy;',
 'IMT Institute for Advanced Studies, Piazza San Francesco 19, 55100 Lucca, Italy; Istituto dei Sistemi Complessi (ISC), Via dei Taurini 19, 00185 Rome, Italy; London Institute for Mathematical Sciences, 35a South St. Mayfair, London W1K 2XF, United Kingdom.',
 'Dipartimento di Biologia e Patologia Molecolare e Cellulare, BioGeM Consortium, Istituto di Endocrinologia ed Oncologia Sperimentale CNR, Università “Federico II,” 80131 Naples, Italy',
 'European Institute of Oncology IRCCS, Department of Experimental Oncology, Milan, Italy.',
 'Center for Biomedicine, European Academy Bozen/Bolzano (EURAC), Bolzano, Italy (Affiliated Institute of the University of Lübeck).,',
 'Institute of Bioimaging and Molecular Physiology, National Research CouncilSegrate, Italy.',
 'European Institute of Oncology IRCCS, 20141, Milan, Italy',
 'Radiology Department, ‘Ospedali Riuniti and University of Trieste’, Trieste 34149, Italy',
 'Center for Biomedicine, European Academy Bozen/Bolzano (EURAC), Bolzano, Italy; Affiliated Institute of the University of Lübeck, Lübeck, Germany.',
 'Instituto Universitario Europeo, Florencia y Universidad de Siena.',
 'Dipartimento di Ingegneria Aerospaziale, Università Federico II, Napoli, Italia',
 'Chirurgia Generale 1, Ospedale Papa Giovanni 23, Bergamo, Italy',
 'Elettra-Sincrotrone Trieste SCpA, SS 14 km 163.5 AREA Science Park, 34149 Basovizza, Trieste, Italy.',
 'European Institute of Oncology, Division of Otolaryngology and Head and Neck Surgery, Milan, Italy',
 'Division of Radiology, European Institute of Oncology, IRCCS, Milan, Italy',
 'Division of Pathology, IEO, European Institute of Oncology IRCCS, 20144 Milan, Italy',
 'European Laboratory for Non-Linear Spectroscopy, University of Florence, Florence, Italy.',
 'Department of Neuroscience and Regenerative Medicine, Medical College of Georgia, Augusta University, Augusta, Georgia 30912.Institute of Hypoxia Medicine and Institute of Neuroscience, Wenzhou Medical University, Wenzhou 325035, China.',
 'Drug Development Program, European Institute of Oncology, Milan, Italy; and',
 'Resident in Anaesthesia and Intensive Care, "Federico II" University, Via Sergio Pansini, 80131, Naples, Campania, Italy.',
 'Association EURATOM-IPP.CR, Institute of Plasma Physics AS CR, v.v.i., Prague, Czech Republic',
 'Neuroimmunology Clinic, Department of Neurology, S. Gerardo Hospital, University of Milan Bicocca, Monza, Italy',
 'Istituto di Radiologia, Università “Federico II”, Napoli, Italy',
 'Dipartimento di Scienze Teoriche e Applicate, Università degli Studi dell’Insubria, Via Giuseppe Mazzini 5, 21100 Varese VA, Italy',
 'Centre de Formation et de Recherche en Aquaculture (CEFRA), Universit de Lige ; 10, chemin de la justice, B-4500 Tihange, Belgique.',
 'Department of Biomedical, Sciences, University of Modena and Reggio Emilia, Via Campi 287, I41100, Modena - Italy. luigiagnati@tin.it.',
 'Università degli Studi di Bologna\r\nUniversidad Santo Tomás',
 'Institute for Applied Physics “Carrara”, National Research Council, 50019 Firenze, Italy',

In [5]:
run_affro('City University of Hong Kong Dongguan')

[{'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/03q8dnn23',
  'name': 'City University of Hong Kong',
  'confidence': 0.8944271909999159,
  'status': 'active',
  'country': ['hong kong']}]

In [9]:
run_affro("School of Information Technology and Mathematical Sciences, University of South Australia, Mawson Lake Campus, Mawson Lakes, SA, Australia")

[{'provenance': 'affro',
  'version': '3.2.5',
  'pid': 'ror',
  'value': 'https://ror.org/01p93h210',
  'name': 'University of South Australia',
  'confidence': 1.0,
  'status': 'inactive',
  'country': ['australia']},
 {'provenance': 'affro',
  'version': '3.2.5',
  'pid': 'ror',
  'value': 'https://ror.org/028g18b61',
  'name': 'Adelaide University',
  'confidence': 1.0,
  'status': 'active',
  'country': ['australia']}]

In [9]:
run_affro("university of athens | university of vienna")

[{'provenance': 'affro',
  'version': '3.3.2',
  'pid': 'ror',
  'value': 'https://ror.org/04gnjpq42',
  'name': 'National and Kapodistrian University of Athens',
  'confidence': 1.0,
  'status': 'active',
  'country': ['greece']},
 {'provenance': 'affro',
  'version': '3.3.2',
  'pid': 'ror',
  'value': 'https://ror.org/03prydq77',
  'name': 'University of Vienna',
  'confidence': 1.0,
  'status': 'active',
  'country': ['austria']}]

In [7]:
run_affro('Universitá degli Studi di Roma Sapienza')

[{'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/02be6w209',
  'name': 'Sapienza University of Rome',
  'confidence': 0.8944271909999159,
  'status': 'active',
  'country': ['italy']}]

In [5]:
import pandas as pd 
dominika = pd.read_json('/Users/myrto/Desktop/crossref_pub.json', lines = True)
dominika['curated'] = [[x] for x in dominika['ror-id'].to_list()]
dominika = dominika.dropna(subset=['organisation-string']).reset_index(drop = True)
len(dominika)

47941

In [4]:
import pandas as pd
import ast
curated_oa = pd.read_csv('/Users/myrto/Documents/openAIRE/15. evaluation/oalex_cwts.csv')

curated_oa['curated'] =  [ast.literal_eval(x) for x in curated_oa['curated']]


#evaluate_micro(curated_oa, 'oalex')

# {'precision': 0.9778166958552248,
#  'recall': 0.7945920303605313,
#  'f1_score': 0.8767338393090814}
oalex = pd.read_csv('/Users/myrto/Documents/openAIRE/openalex/openalex_cur_results.csv')
oalex_rors = [x.split(';') if type(x) == str else [] for x in oalex['predicted_ror_id']]
oalex['oalex_rors'] = oalex_rors
curated_oa = pd.merge(curated_oa, oalex, on = 'affiliation_string')[['affiliation_string','curated','oalex_rors']]
curated_oa['curated'] = [list(set(x)) for x in curated_oa['curated']]
len(curated_oa)

new = [['https://ror.org/05n3x4p02', 'https://ror.org/05f0zr486'],
['https://ror.org/05cz70a34', 'https://ror.org/03prydq77', 'https://ror.org/04khwmr87'],
['https://ror.org/00892tw58', 'https://ror.org/00carf720'],
['https://ror.org/01ej9dk98', 'https://ror.org/005bvs909'],
['https://ror.org/01ej9dk98', 'https://ror.org/005bvs909'],
['https://ror.org/02rktxt32', 'https://ror.org/01ej9dk98', 'https://ror.org/048fyec77'],
['https://ror.org/03grnna41', 'https://ror.org/01ej9dk98'],
['https://ror.org/0484pjq71', 'https://ror.org/02bfwt286'],
['https://ror.org/0384j8v12', 'https://ror.org/05gpvde20'],
['https://ror.org/02gs2e959', 'https://ror.org/0384j8v12'],
['https://ror.org/02gs2e959'],
['https://ror.org/00eae9z71', 'https://ror.org/0187t0j49'],
['https://ror.org/03r8z3t63', 'https://ror.org/03zzzks34'],
['https://ror.org/02bfwt286', 'https://ror.org/036s9kg65'],
['https://ror.org/02bfwt286', 'https://ror.org/036s9kg65'],
['https://ror.org/02bfwt286', 'https://ror.org/036s9kg65'],
['https://ror.org/02bfwt286', 'https://ror.org/036s9kg65'],
['https://ror.org/0384j8v12', 'https://ror.org/03vb6df93'],
['https://ror.org/00rqy9422', 'https://ror.org/04mqb0968'],
['https://ror.org/01bsaey45', 'https://ror.org/0384j8v12'],
['https://ror.org/03yxgmm62', 'https://ror.org/047272k79'],
['https://ror.org/04gp5yv64', 'https://ror.org/0384j8v12'],
['https://ror.org/01ej9dk98', 'https://ror.org/001kjn539'],
['https://ror.org/001kjn539'],
['https://ror.org/01ej9dk98', 'https://ror.org/008q4kt04', 'https://ror.org/01sqdef20'],
['https://ror.org/00892tw58', 'https://ror.org/00x362k69'],
['https://ror.org/02tj04e91', 'https://ror.org/03r8z3t63'],
['https://ror.org/01ej9dk98', 'https://ror.org/05dbj6g52'],
['https://ror.org/01ej9dk98', 'https://ror.org/05dbj6g52'],
['https://ror.org/02495e989', 'https://ror.org/03s4khd80'],
['https://ror.org/05j1gs298', 'https://ror.org/01r9htc13'],
['https://ror.org/008x57b05', 'https://ror.org/01hwamj44'],
['https://ror.org/00afp2z80', 'https://ror.org/044s61914'],
['https://ror.org/05cmp5q80', 'https://ror.org/01r9htc13'],
['https://ror.org/041yk2d64', 'https://ror.org/010we4y38', 'https://ror.org/02x6jsy35'],
['https://ror.org/00hrmgq26', 'https://ror.org/0198v2949'],
['https://ror.org/03490as77', 'https://ror.org/04pznag94'],
['https://ror.org/036rp1748'],
['https://ror.org/009z39p97', 'https://ror.org/02fa3aq29'],
['https://ror.org/02rkgge26', 'https://ror.org/04m7cgp86', 'https://ror.org/02grkyz14'],
['https://ror.org/03dbr7087', 'https://ror.org/05deks119'],
['https://ror.org/04skqfp25', 'https://ror.org/03dbr7087'],
['https://ror.org/04skqfp25'],
['https://ror.org/04skqfp25', 'https://ror.org/03dbr7087'],
['https://ror.org/03wefcv03', 'https://ror.org/03dbr7087'],
['https://ror.org/05n0tzs53', 'https://ror.org/03dbr7087'],
['https://ror.org/042xt5161', 'https://ror.org/03dbr7087'],
['https://ror.org/042xt5161', 'https://ror.org/03dbr7087', 'https://ror.org/03qv8yq19'],
['https://ror.org/042xt5161', 'https://ror.org/03dbr7087', 'https://ror.org/03zayce58'],
['https://ror.org/042xt5161', 'https://ror.org/03dbr7087', 'https://ror.org/043q8yx54'],
['https://ror.org/042xt5161', 'https://ror.org/03dbr7087'],
['https://ror.org/04cm2y595', 'https://ror.org/03dbr7087', 'https://ror.org/042xt5161'],
['https://ror.org/042xt5161', 'https://ror.org/03dbr7087', 'https://ror.org/03zayce58', 'https://ror.org/043q8yx54'],
['https://ror.org/042xt5161', 'https://ror.org/03dbr7087', 'https://ror.org/03qv8yq19'],
['https://ror.org/04wc5jk96', 'https://ror.org/01pxwe438'],
['https://ror.org/04cpxjv19', 'https://ror.org/04wc5jk96'],
['https://ror.org/04wc5jk96', 'https://ror.org/01pxwe438'],
['https://ror.org/04wc5jk96', 'https://ror.org/01pxwe438'],
['https://ror.org/04cpxjv19', 'https://ror.org/04wc5jk96'],
['https://ror.org/04cpxjv19', 'https://ror.org/04wc5jk96'],
['https://ror.org/04cpxjv19', 'https://ror.org/04gbhgc79'],
['https://ror.org/04gbhgc79', 'https://ror.org/01pxwe438'],
['https://ror.org/02xerpt86', 'https://ror.org/02gfys938', 'https://ror.org/05pr37258'],
['https://ror.org/00wg2b048', 'https://ror.org/010x8gc63'],
['https://ror.org/057q4rt57', 'https://ror.org/03dbr7087'],
['https://ror.org/057q4rt57', 'https://ror.org/03dbr7087'],
['https://ror.org/02j6fbg68', 'https://ror.org/03dbr7087', 'https://ror.org/057q4rt57'],
['https://ror.org/057q4rt57', 'https://ror.org/03dbr7087'],
['https://ror.org/056jjra10', 'https://ror.org/01pxwe438'],
['https://ror.org/056jjra10', 'https://ror.org/01pxwe438'],
['https://ror.org/026pg9j08', 'https://ror.org/03dbr7087'],
['https://ror.org/026pg9j08', 'https://ror.org/03dbr7087'],
['https://ror.org/026pg9j08', 'https://ror.org/03dbr7087'],
['https://ror.org/042xt5161', 'https://ror.org/03dbr7087', 'https://ror.org/026pg9j08'],
['https://ror.org/01gv74p78', 'https://ror.org/0161xgx34'],
['https://ror.org/03dbr7087', 'https://ror.org/03zayce58'],
['https://ror.org/03dbr7087', 'https://ror.org/03zayce58'],
['https://ror.org/03dbr7087', 'https://ror.org/03zayce58'],
['https://ror.org/03dbr7087', 'https://ror.org/03zayce58'],
['https://ror.org/03dbr7087', 'https://ror.org/03zayce58'],
['https://ror.org/03dbr7087', 'https://ror.org/03zayce58'],
['https://ror.org/03dbr7087', 'https://ror.org/03zayce58'],
['https://ror.org/042xt5161', 'https://ror.org/03zayce58'],
['https://ror.org/042xt5161', 'https://ror.org/03zayce58'],
['https://ror.org/0160cpw27', 'https://ror.org/013e81n30'],
['https://ror.org/03rmrcq20', 'https://ror.org/03bd8jh67', 'https://ror.org/04htzww22'],
['https://ror.org/04n901w50', 'https://ror.org/03rmrcq20'],
['https://ror.org/04n901w50', 'https://ror.org/03rmrcq20'],
['https://ror.org/05a353079', 'https://ror.org/019whta54'],
['https://ror.org/01462r250', 'https://ror.org/02crff812'],
['https://ror.org/037xabw57', 'https://ror.org/02crff812'],
['https://ror.org/01462r250', 'https://ror.org/02crff812'],
['https://ror.org/01462r250'],
['https://ror.org/01462r250', 'https://ror.org/02crff812'],
['https://ror.org/01m1pv723'],
['https://ror.org/01m1pv723', 'https://ror.org/01swzsf04'],
['https://ror.org/01m1pv723', 'https://ror.org/01swzsf04'],
['https://ror.org/02crff812', 'https://ror.org/02yzaka98'],
['https://ror.org/02crff812', 'https://ror.org/02yzaka98'],
['https://ror.org/02crff812', 'https://ror.org/035vb3h42'],
['https://ror.org/01q9sj412', 'https://ror.org/02k7v4d05'],
['https://ror.org/01q9sj412', 'https://ror.org/02k7v4d05'],
['https://ror.org/01q9sj412', 'https://ror.org/02k7v4d05'],
['https://ror.org/01q9sj412', 'https://ror.org/02k7v4d05'],
['https://ror.org/01q9sj412', 'https://ror.org/02k7v4d05'],
['https://ror.org/01q9sj412', 'https://ror.org/02k7v4d05'],
['https://ror.org/01q9sj412', 'https://ror.org/02k7v4d05'],
['https://ror.org/04tavpn47'],
['https://ror.org/01rxvg760'],
['https://ror.org/04kmpyd03', 'https://ror.org/01rxvg760'],
['https://ror.org/04kmpyd03', 'https://ror.org/01rxvg760'],
['https://ror.org/04kmpyd03', 'https://ror.org/01rxvg760'],
['https://ror.org/04kmpyd03', 'https://ror.org/01rxvg760'],
['https://ror.org/04kmpyd03', 'https://ror.org/01rxvg760'],
['https://ror.org/04kmpyd03', 'https://ror.org/01rxvg760']]
affro_new = [run_affro(curated_oa['affiliation_string'].iloc[i]) for i in range(len(curated_oa))]
#affro_nlp = [find_ror_simple_nlp(curated_oa['affiliation_string'].iloc[i], 0.55, 0.875) for i in range(len(curated_oa))]
#{‘limit’: 650, ‘rad’: 4, ‘simg’: 0.8666871603229694, ‘simu’: 0.5232609407233944}


curated_oa['affro_new'] = affro_new
#curated_oa['affro_nlp'] = affro_nlp

affro_rors_active = [list(set([x['value']  for x in curated_oa['affro_new'].iloc[i] if x['status'] == 'active'])) for i in range(len(curated_oa))]
curated_oa['affro_rors_active'] =  affro_rors_active

#curated_active = [list(set([x['Value']  for x in curated_oa['curated'].iloc[i] if x['Status'] == 'active'])) for i in range(len(curated_oa))]

affro_rors_all = [[x['value']   for x in curated_oa['affro_new'].iloc[i]] for i in range(len(curated_oa))]

curated_oa['affro_rors__all'] =  affro_rors_all

In [5]:
curated_oa_115 = curated_oa[0:115].copy()
curated_oa_115['curated'] = new
affro_115= [run_affro(curated_oa_115['affiliation_string'].iloc[i]) for i in range(len(curated_oa_115))]
curated_oa_115['affro_new'] = affro_115
#curated_oa['affro_nlp'] = affro_nlp

affro_rors_active = [list(set([x['value']  for x in curated_oa_115['affro_new'].iloc[i] if x['status'] == 'active'])) for i in range(len(curated_oa_115))]
curated_oa_115['affro_rors_active'] =  affro_rors_active

# {'precision': np.float64(0.995475113122172),
#  'recall': np.float64(0.9243697478991597),
#  'f1_score': np.float64(0.9586056644880174)}

# full

# {'precision': np.float64(0.923262839879154),
#  'recall': np.float64(0.7252017085904129),
#  'f1_score': np.float64(0.8123338649654439)}

In [8]:
evaluate_micro(curated_oa_115,'affro_rors_active') # replace all|

{'precision': np.float64(0.9732142857142857),
 'recall': np.float64(0.9159663865546218),
 'f1_score': np.float64(0.9437229437229437)}

In [19]:
run_affro("'Centre for Research in Neuroscience, Department of Neurology and Neurosurgery, The Research Institute of the McGill University Health Centre, Montreal General Hospital, Montreal, QC, Canada H3G 1A4'")

[{'provenance': 'affro',
  'version': '3.2.7',
  'pid': 'ror',
  'value': 'https://ror.org/04pemf943',
  'name': 'Research Institute of the McGill University Health Centre',
  'confidence': 1.0,
  'status': 'active',
  'country': ['canada']},
 {'provenance': 'affro',
  'version': '3.2.7',
  'pid': 'ror',
  'value': 'https://ror.org/04gbhgc79',
  'name': 'Montreal General Hospital',
  'confidence': 1.0,
  'status': 'active',
  'country': ['canada']}]

In [17]:
curated_oa_115[curated_oa_115['FP_affro_rors_active']>0]

,affiliation_string,curated,oalex_rors,affro_new,affro_rors_active,affro_rors__all,TP_affro_rors_active,FP_affro_rors_active,FN_affro_rors_active
10,"John Walsh Centre for Rehabilitation Research,...",[https://ror.org/02gs2e959],[https://ror.org/02gs2e959],"[{'provenance': 'affro', 'version': '3.2.5', '...","[https://ror.org/03bpc5f92, https://ror.org/02...","[https://ror.org/03bpc5f92, https://ror.org/02...",1,1,0

In [16]:
len(curated_oa_115[curated_oa_115['FP_affro_rors_active']>0])

1

In [6]:
affro_results = [run_affro(dominika['organisation-string'].iloc[i]) for i in range(len(dominika))]
# #precision {'Value: 0.9798873692679002', 'Time: 48.39s'} {'rad': 6, 'simg': 0.900930416439436, 'simu': 0.9026075527296151, 'specific': True}
# #f1 {'Value: 0.9368932038834951', 'Time: 42.16s'} {'rad': 3, 'simg': 0.8274723226476576, 'simu': 0.4257863721189187, 'specific': True}
# #recall {'Value: 0.9171159029649596', 'Time: 43.95s'} {'rad': 3, 'simg': 0.662045060060588, 'simu': 0.31273458633304524, 'specific': True}
#  #0.7028064142049635, 'simu': 0.3331579633213647
dominika['affro_new'] = affro_results
affro_rors_active = [list(set([x['value']  for x in dominika['affro_new'].iloc[i] if x['status'] == 'active'])) for i in range(len(dominika))]
dominika['affro_rors_active'] =  affro_rors_active
affro_rors_all = [[x['value']   for x in dominika['affro_new'].iloc[i]] for i in range(len(dominika))]

dominika['affro_rors_all'] =  affro_rors_all

# {'precision': np.float64(0.809568418988693),
#  'recall': np.float64(0.7751194176174881),
#  'f1_score': np.float64(0.7919694806163551)}

In [7]:
run_affro("Fraunhofer - Institut für zerstörungsfreie Prüfverfahren, Universität, Gebäude 37, D-66123 SAARBRüCKEN, F. R. Germany (Part 5)")

[]

In [8]:
evaluate_micro(dominika, 'affro_rors_active')

{'precision': np.float64(0.8013756287855456),
 'recall': np.float64(0.8141465551406938),
 'f1_score': np.float64(0.8077106139933364)}

In [9]:
dominika['len'] = [len(x) for x in dominika['affro_rors_active'].to_list()]
dom1 = dominika[dominika['len'] ==1].reset_index(drop = True)
evaluate_micro(dom1, 'affro_rors_active') #  may

{'precision': np.float64(0.9092219775610779),
 'recall': np.float64(0.9092219775610779),
 'f1_score': np.float64(0.9092219775610779)}

In [10]:
len(dominika[dominika['len']>0])

42993

In [11]:
evaluate_micro(dominika, 'affro_rors_active') #  version (full) ror april replacements all

{'precision': np.float64(0.8013756287855456),
 'recall': np.float64(0.8141465551406938),
 'f1_score': np.float64(0.8077106139933364)}

In [12]:
run_affro("Integrative Program for Biological and Genome Sciences, University of North Carolina 2, Chapel Hill, NC,")

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/02yf2ch17',
  'name': 'Carroll University',
  'confidence': 0.5773502691896258,
  'status': 'active',
  'country': ['united states']}]

In [13]:
run_affro("Laboratoire de Chimie Quantique, UMR 7551 CNRS/ULP, Université Louis Pasteur, 4 rue Blaise Pascal, 67000 Strasbourg, France.")

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/04asdee31',
  'name': 'Université Marie et Louis Pasteur',
  'confidence': 0.8660254037844388,
  'status': 'active',
  'country': ['france']}]

In [11]:
'zu' in stop

NameError: name 'stop' is not defined

In [20]:
run_affro('Institute of Clinical Molecular Biology, Christian-Albrechts-University Kiel, Kiel, Germany')

[{'provenance': 'affro',
  'version': '3.2.7',
  'pid': 'ror',
  'value': 'https://ror.org/05kxtq558',
  'name': 'Institute of Molecular Biology',
  'confidence': 0.8660254037844388,
  'status': 'active',
  'country': ['germany']},
 {'provenance': 'affro',
  'version': '3.2.7',
  'pid': 'ror',
  'value': 'https://ror.org/04v76ef78',
  'name': 'Christian-Albrechts-Universität zu Kiel',
  'confidence': 1.0,
  'status': 'active',
  'country': ['germany']}]

In [21]:
run_affro("Εθνικό και Καποδιστριακό Πανεπιστήμιο Αθηνών|Πανεπιστήμιο Δυτικής Αττικής, Τμήμα Κοινωνικής Εργασίας")

[{'provenance': 'affro',
  'version': '3.2.7',
  'pid': 'ror',
  'value': 'https://ror.org/04gnjpq42',
  'name': 'National and Kapodistrian University of Athens',
  'confidence': 1.0,
  'status': 'active',
  'country': ['greece']},
 {'provenance': 'affro',
  'version': '3.2.7',
  'pid': 'ror',
  'value': 'https://ror.org/00r2r5k05',
  'name': 'University of West Attica',
  'confidence': 1.0,
  'status': 'active',
  'country': ['greece']}]

In [22]:
run_affro('TTaiwan Agricultural Research Institute, Applied Zoology Division, Council of Agriculture, Wufeng District, Taichung City, Taiwan')

[{'provenance': 'affro',
  'version': '3.2.7',
  'pid': 'ror',
  'value': 'https://ror.org/02wget071',
  'name': 'Taiwan Agricultural Research Institute Council of Agriculture, Executive Yuan',
  'confidence': 0.7071067811865475,
  'status': 'active',
  'country': ['taiwan']},
 {'provenance': 'affro',
  'version': '3.2.7',
  'pid': 'ror',
  'value': 'https://ror.org/0358yps07',
  'name': 'Council of Agriculture',
  'confidence': 1.0,
  'status': 'active',
  'country': ['taiwan']}]

In [5]:
run_affro("[2] Tecnológico Nacional de México/I. T. De Milpa Alta")

[{'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/00davry38',
  'name': 'Tecnológico Nacional de México',
  'confidence': 1.0,
  'status': 'active',
  'country': ['mexico']}]

In [24]:
run_affro("From the William Harvey Research Institute j, Barts and The London School of Medicine and Dentistry, Queen Mary University of London (K.J.B., S.L.T., R.S.B., A.J.H.); and Centre for Clinical Pharmacology, University College London (J.P., L.H.C., R.J.M.), London, United Kingdom.")

[{'provenance': 'affro',
  'version': '3.2.7',
  'pid': 'ror',
  'value': 'https://ror.org/0574dzy90',
  'name': 'William Harvey Research Institute',
  'confidence': 1.0,
  'status': 'active',
  'country': ['united kingdom']},
 {'provenance': 'affro',
  'version': '3.2.7',
  'pid': 'ror',
  'value': 'https://ror.org/026zzn846',
  'name': 'Queen Mary University of London',
  'confidence': 1.0,
  'status': 'active',
  'country': ['united kingdom']},
 {'provenance': 'affro',
  'version': '3.2.7',
  'pid': 'ror',
  'value': 'https://ror.org/02jx3x895',
  'name': 'University College London',
  'confidence': 1.0,
  'status': 'active',
  'country': ['united kingdom']}]

In [25]:
run_affro('Center for Coastal Fisheries and Habitat Research, National Ocean Service, National Oceanic and Atmospheric Administration, Beaufort, NC 28516; and')

[]

In [26]:
run_affro('Child and Adolescent Mental Health Initiative (CAMHI), Stavros Niarchos Foundation and Child Mind Institute, Athens, Greece.Child Mind Institute, 215 E 50th St, New York, NY, 10022, USA.')

[{'provenance': 'affro',
  'version': '3.2.7',
  'pid': 'ror',
  'value': 'https://ror.org/0210rze73',
  'name': 'Stavros Niarchos Foundation',
  'confidence': 1.0,
  'status': 'active',
  'country': ['greece']},
 {'provenance': 'affro',
  'version': '3.2.7',
  'pid': 'ror',
  'value': 'https://ror.org/01bfgxw09',
  'name': 'Child Mind Institute',
  'confidence': 1.0,
  'status': 'active',
  'country': ['united states']}]

In [6]:
run_affro("Iaso Children's Hospital (A.P.), Athens, Greece; Queen's University Belfast (O.P.), UK; ")

[{'provenance': 'affro',
  'version': '3.2.3',
  'pid': 'ror',
  'value': 'https://ror.org/059dpw236',
  'name': 'Iaso Children’s Hospital',
  'confidence': 1.0,
  'status': 'active',
  'country': ['greece']},
 {'provenance': 'affro',
  'version': '3.2.3',
  'pid': 'ror',
  'value': 'https://ror.org/00hswnk62',
  'name': "Queen's University Belfast",
  'confidence': 1.0,
  'status': 'active',
  'country': ['united kingdom']}]

In [5]:
run_affro('Attica Psychiatric Hospital Dromokaiteio Dromokaiteio Psychiatric Hospital of Athens')

[{'provenance': 'affro',
  'version': '3.2.3',
  'pid': 'openorgs',
  'value': 'openorgs____::0000103523',
  'name': 'Dromokaiteio Psychiatric Hospital of Athens',
  'confidence': 0.9258200997725516,
  'status': 'active',
  'country': ['greence']}]

In [18]:
run_affro('Department of Neurology, Bundang Jesaeng General Hospital, Daejin Medical Center, Seongnam,  Korea')

[{'provenance': 'affro',
  'version': '3.2.0',
  'pid': 'ror',
  'value': 'https://ror.org/03z0bdc81',
  'name': 'Bundang Jesaeng Hospital',
  'confidence': 1.0,
  'status': 'active',
  'country': 'south korea'}]

In [ ]:
run_affro("Centro Científico Tecnológico - Bahía Blanca, CONICET, Bahía Blanca, Argentina")

[{'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/03efzvv60',
  'name': 'Centro Científico Tecnológico - Bahía Blanca',
  'confidence': 1.0,
  'status': 'active',
  'country': ['argentina']},
 {'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/03cqe8w59',
  'name': 'Consejo Nacional de Investigaciones Científicas y Técnicas',
  'confidence': 1.0,
  'status': 'active',
  'country': ['argentina']}]

In [16]:
run_affro("Centro de Investigaciones en Química Biológica de Córdoba (CIQUIBIC), UNC CONICET, Departamento de Química Biológica, Facultad de Ciencias Químicas, Universidad Nacional de Córdoba, 5000, Ciudad Universitaria, Córdoba, Argentina")

[{'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/023dgw813',
  'name': 'Research Centre in Biological Chemistry of Córdoba',
  'confidence': 1.0,
  'status': 'active',
  'country': ['argentina']},
 {'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/056tb7j80',
  'name': 'Universidad Nacional de Córdoba',
  'confidence': 1.0,
  'status': 'active',
  'country': ['argentina']}]

In [8]:
run_affro("The First Bethune Hospital and Institute of Immunology, Jilin University, Changchun, China")

[{'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/00js3aw79',
  'name': 'Jilin University',
  'confidence': 1.0,
  'status': 'active',
  'country': ['china']}]

In [4]:
  


import pandas as pd
import ast 
dataset = pd.read_csv('/Users/myrto/Documents/openAIRE/gitea/finalize_dict/test_feb26.csv')
#dataset = pd.read_csv('/Users/myrto/Documents/openAIRE/gitea/affRo/test_upd.csv')

dataset['curated'] =  [ast.literal_eval(x) for x in dataset['curated']]

#affro_results = [affro_config(dataset['raw_affiliation_string'].iloc[i], 4,0.5232609407233944,0.86668716032296, 250) for i in range(len(dataset))]
affro_results = [run_affro(dataset['raw_affiliation_string'].iloc[i]) for i in range(len(dataset))]
#{‘limit’: 650, ‘rad’: 4, ‘simg’: 0.8666871603229694, ‘simu’: 0.5232609407233944}

dataset['affro_results'] = affro_results 

#restrict to active links:

affro_rors_active = [list(set([x['value']  for x in dataset['affro_results'].iloc[i] if x['status'] == 'active'])) for i in range(len(dataset))]

dataset['affro_rors_active'] =  affro_rors_active

PermissionError: [Errno 1] Operation not permitted: '/Users/myrto/Documents/openAIRE/gitea/finalize_dict/test_feb26.csv'

In [3]:
evaluate_micro(dataset, 'affro_rors_active') #  version (full) ror april replacements all

{'precision': np.float64(0.972972972972973),
 'recall': np.float64(0.9310344827586207),
 'f1_score': np.float64(0.9515418502202643)}

In [4]:
run_affro('Department of Science, "Roma Tre"University, Viale Marconi, 446, 00146 Roma, Italy.')

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/05vf0dg29',
  'name': 'Roma Tre University',
  'confidence': 0.8660254037844388,
  'status': 'active',
  'country': ['italy']}]

In [5]:
run_affro('Istituto di Linguistica Computazionale "A. Zampolli," CNR of Pisa')

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/028g3pe33',
  'name': 'Institute for Computational Linguistics “A. Zampolli”',
  'confidence': 1.0,
  'status': 'active',
  'country': ['italy']},
 {'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/04zaypm56',
  'name': 'National Research Council',
  'confidence': 1.0,
  'status': 'active',
  'country': ['italy']}]

In [6]:
run_affro('Universidade Federal do Paraná, Brasil; Università degli Studi di Roma, Itália')

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/037263487',
  'name': 'Università degli Studi Internazionali di Roma',
  'confidence': 0.8660254037844388,
  'status': 'active',
  'country': ['italy']}]

In [7]:
dataset[dataset['FN_affro_rors_active']>0].index

Index([  10,   28,   53,   54,   59,   65,   67,   71,   87,   89,  103,  109,
        114,  117,  119,  120,  128,  135,  150,  151,  160,  161,  165,  168,
        170,  175,  178,  181,  186,  191,  192,  198,  212,  235,  263,  275,
        281,  284,  287,  321,  327,  342,  347,  373,  382,  428,  460,  492,
        511,  546,  560,  622,  648,  677,  689,  729,  735,  737,  746,  773,
        833,  837,  848,  884,  951,  966,  973, 1082, 1083, 1084, 1094, 1096,
       1097, 1098, 1114, 1125, 1127, 1129, 1130, 1143, 1148, 1164, 1165, 1172,
       1175, 1176, 1177, 1178, 1257, 1326, 1327, 1332, 1342, 1367],
      dtype='int64')

In [8]:
run_affro('5Fundació Institut d’Investigació en Ciències de la Salut Germans Trias i Pujol, Barcelona, Spain')

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/03bzdww12',
  'name': "Institut d'Investigació en Ciències de la Salut Germans Trias i Pujol",
  'confidence': 0.9486832980505138,
  'status': 'active',
  'country': ['spain']}]

In [9]:
run_affro("Central European Institute of Technology (CEITEC) Masaryk University  Brno Czech Republic")

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/009nz6031',
  'name': 'Central European Institute of Technology – Masaryk University',
  'confidence': 0.816496580927726,
  'status': 'active',
  'country': ['czechia']}]

In [10]:
dataset[dataset['FN_affro_rors_active'] > 0].index

Index([  10,   28,   53,   54,   59,   65,   67,   71,   87,   89,  103,  109,
        114,  117,  119,  120,  128,  135,  150,  151,  160,  161,  165,  168,
        170,  175,  178,  181,  186,  191,  192,  198,  212,  235,  263,  275,
        281,  284,  287,  321,  327,  342,  347,  373,  382,  428,  460,  492,
        511,  546,  560,  622,  648,  677,  689,  729,  735,  737,  746,  773,
        833,  837,  848,  884,  951,  966,  973, 1082, 1083, 1084, 1094, 1096,
       1097, 1098, 1114, 1125, 1127, 1129, 1130, 1143, 1148, 1164, 1165, 1172,
       1175, 1176, 1177, 1178, 1257, 1326, 1327, 1332, 1342, 1367],
      dtype='int64')

In [9]:
dataset[dataset['FP_affro_rors_active'] > 0].index

Index([  10,   28,   47,   53,   59,  109,  120,  128,  135,  139,  151,  153,
        155,  179,  191,  216,  233,  241,  269,  321,  327,  342,  347,  357,
        437,  454,  546,  622,  729,  870,  895,  899,  939,  941,  942, 1018,
       1033, 1096, 1100, 1115, 1127, 1132, 1153, 1163, 1175, 1177, 1276],
      dtype='int64')

In [11]:
run_affro(dataset['raw_affiliation_string'].iloc[949])

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/00saywf64',
  'name': 'Gyeongsang National University',
  'confidence': 1.0,
  'status': 'active',
  'country': ['south korea']}]

In [12]:
run_affro( 'Institute of Virology, University of Bonn Medical Centre')

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/041nas322',
  'name': 'University of Bonn',
  'confidence': 0.7071067811865475,
  'status': 'active',
  'country': ['germany']}]

In [13]:
run_affro('University Department of Medicine and Infectious Diseases Service, Kantonsspital Baselland, University of Basel, Bruderholz, Switzerland')

[{'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/00b747122',
  'name': 'Kantonsspital Baselland',
  'confidence': 1.0,
  'status': 'active',
  'country': ['switzerland']},
 {'provenance': 'affro',
  'version': '3.3.3',
  'pid': 'ror',
  'value': 'https://ror.org/02s6k3f65',
  'name': 'University of Basel',
  'confidence': 1.0,
  'status': 'active',
  'country': ['switzerland']}]

In [14]:
dataset2 = pd.read_csv('/Users/myrto/Documents/openAIRE/github/matching/aff/aff_test.csv')[0:23]
#dataset = pd.read_csv('/Users/myrto/Documents/openAIRE/gitea/affRo/test_upd.csv')

dataset2['curated'] =  [ast.literal_eval(x) for x in dataset2['curated']]

affro_results = [run_affro(dataset2['raw_affiliation_string'].iloc[i]) for i in range(len(dataset2))]

dataset2['affro_results'] = affro_results 

#restrict to active links:

affro_rors_active = [list(set([x['value']  for x in dataset2['affro_results'].iloc[i] if x['status'] == 'active'])) for i in range(len(dataset2))]

dataset2['affro_rors_active'] =  affro_rors_active


evaluate_micro(dataset2, 'affro_rors_active') #  version (full) ror april replacements all

{'precision': np.float64(0.9333333333333333),
 'recall': np.float64(1.0),
 'f1_score': np.float64(0.9655172413793104)}

In [7]:
create_df_algorithm('St James Hospital and Trinity College Dublin, Dublin, IRL',4)

NameError: name 'create_df_algorithm' is not defined

In [6]:
dataset2

,Unnamed: 0,raw_affiliation_string,curated,affro_results,affro_rors_active,TP_affro_rors_active,FP_affro_rors_active,FN_affro_rors_active
0,0,"Department of Internal Medicine, Division of I...",[https://ror.org/01r024a98],"[{'provenance': 'affro', 'version': '3.2.0', '...",[https://ror.org/01r024a98],1,0,0
1,1,dpet. of chemistry university of california lo...,[https://ror.org/046rm7j60],"[{'provenance': 'affro', 'version': '3.2.0', '...",[https://ror.org/046rm7j60],1,0,0
2,2,"Institut f\u00fcr Physik Augsburg, germany",[openorgs____::0000103110],"[{'provenance': 'affro', 'version': '3.2.0', '...",[openorgs____::0000103110],1,0,0
3,3,google (United States),[https://ror.org/00njsd438],"[{'provenance': 'affro', 'version': '3.2.0', '...",[https://ror.org/00njsd438],1,0,0
4,4,google (UK),[https://ror.org/024bc3e07],"[{'provenance': 'affro', 'version': '3.2.0', '...",[https://ror.org/024bc3e07],1,0,0
5,5,google (United Kingdom),[https://ror.org/024bc3e07],"[{'provenance': 'affro', 'version': '3.2.0', '...",[https://ror.org/024bc3e07],1,0,0
6,6,Copernicus Institute of Sustainable Developmen...,"[openorgs____::0000102848, https://ror.org/04p...","[{'provenance': 'affro', 'version': '3.2.0', '...","[https://ror.org/04pp8hn57, openorgs____::0000...",2,0,0
7,7,"The Hamilton Institute, NUI Maynooth, Maynooth...","[openorgs____::0000103431, https://ror.org/048...","[{'provenance': 'affro', 'version': '3.2.0', '...","[openorgs____::0000103431, https://ror.org/048...",2,0,0
8,8,"The Hamilton Institute, NUI Maynooth, Maynooth...","[openorgs____::0000103431, https://ror.org/048...","[{'provenance': 'affro', 'version': '3.2.0', '...","[openorgs____::0000103431, https://ror.org/048...",2,0,0
9,9,"Mater Misericordiae Hospital, Breast Surgery, ...",[https://ror.org/040hqpc16],[],[],0,0,1
10,10,"Alkermes, Dublin, Ireland",[https://ror.org/05sa44m96],[],[],0,0,1
11,11,First Affiliated Hospital of Xi’an Jiaotong Un...,[https://ror.org/02tbvhh96],"[{'provenance': 'affro', 'version': '3.2.0', '...",[https://ror.org/02tbvhh96],1,0,0
12,12,"St James Hospital and Trinity College Dublin, ...","[https://ror.org/04c6bry31, https://ror.org/02...","[{'provenance': 'affro', 'version': '3.2.0', '...","[https://ror.org/02tyrky19, https://ror.org/04...",2,0,0
13,13,"Institute for Industrial Systems Innovation, S...",[https://ror.org/04h9pn542],"[{'provenance': 'affro', 'version': '3.2.0', '...",[https://ror.org/04h9pn542],1,0,0
14,14,Riley Hospital for Children at Indiana Univers...,"[https://ror.org/03vzvbw58, https://ror.org/02...","[{'provenance': 'affro', 'version': '3.2.0', '...","[https://ror.org/02ets8c94, https://ror.org/03...",2,0,0
15,15,"Institute of Zoology, Ministry of Science and ...",[https://ror.org/05vghhr25],"[{'provenance': 'affro', 'version': '3.2.0', '...",[https://ror.org/05vghhr25],1,0,0
16,16,"Department of Anesthesiology, Aarhus Universit...",[https://ror.org/040r8fr65],"[{'provenance': 'affro', 'version': '3.2.0', '...",[https://ror.org/040r8fr65],1,0,0
17,17,"Institute of Clinical Molecular Biology, Chris...",[https://ror.org/04v76ef78],"[{'provenance': 'affro', 'version': '3.2.0', '...","[https://ror.org/05kxtq558, https://ror.org/04...",1,1,0
18,18,"[2] Tecnológico Nacional de México, I. T. De M...",[https://ror.org/00davry38],"[{'provenance': 'affro', 'version': '3.2.0', '...",[https://ror.org/00davry38],1,0,0

In [9]:
evaluate_micro(dataset, 'affro_rors_active') #  version (full) ror april replacements all

{'precision': np.float64(0.9743589743589743),
 'recall': np.float64(0.9323607427055703),
 'f1_score': np.float64(0.9528973229413759)}

In [10]:
run_affro("Biomedical Research Institute, Seoul d National University Hospital, Seoul, Republic of Korea 1")

[{'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/01z4nnt86',
  'name': 'Seoul National University Hospital',
  'confidence': 1.0,
  'status': 'active',
  'country': ['south korea']},
 {'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/03j7gdf68',
  'name': 'Mogam Institute for Biomedical Research',
  'confidence': 0.8660254037844388,
  'status': 'active',
  'country': ['south korea']}]

In [11]:
for i in dataset[dataset['FN_affro_rors_active']>0].index:
    print(i)
    print(dataset['raw_affiliation_string'].iloc[i])
    print(run_affro(dataset['raw_affiliation_string'].iloc[i]))
    print(dataset['curated'].iloc[i])
    print("\n")

10
1Department of Radiation Oncology, Washington University School of Medicine, St. Louis, Missouri.
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/03ymk3103', 'name': 'University of Washington School of Medicine', 'confidence': 1.0, 'status': 'withdrawn', 'country': 'united states'}, {'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/00cvxb145', 'name': 'University of Washington', 'confidence': 1.0, 'status': 'active', 'country': 'united states'}]
['https://ror.org/01yc7t268']


42
5Fundació Institut d’Investigació en Ciències de la Salut Germans Trias i Pujol, Barcelona, Spain
[]
['https://ror.org/03bzdww12']


53
7Department of Surgery, University of Washington, St. Louis, Missouri;
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/00cvxb145', 'name': 'University of Washington', 'confidence': 1.0, 'status': 'active', 'country': 'united states'}]
['https://ror.org/01yc7t268']


54
7Ludwig Center at Harvard, Boston, Massachusetts.
[]
['https://ror.org/03vek6s52']


59
9Alvin J. Siteman Center, Washington University School of Medicine, St. Louis, Missouri.
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/03ymk3103', 'name': 'University of Washington School of Medicine', 'confidence': 1.0, 'status': 'withdrawn', 'country': 'united states'}, {'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/00cvxb145', 'name': 'University of Washington', 'confidence': 1.0, 'status': 'active', 'country': 'united states'}, {'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/03jrmgg47', 'name': 'Alvin J. Siteman Cancer Center', 'confidence': 0.8660254037844388, 'status': 'active', 'country': 'united states'}]
['https://ror.org/01yc7t268']


65
AFRU711 HPW/RHPB, Wright-Patterson Air Force Base, Dayton, Ohio 45433, United States
[]
['https://ror.org/0097e1k27']


67
AMO GmbH, Gesellschaft für Angewandte Mikro- und Optoelektronik 3 , 52074 Aachen, Germany
[]
['https://ror.org/01sd0e661']


71
Abdus Salam ICTP, Strada Costiera 11, Trieste 34014, Italy
[]
['https://ror.org/009gyvm78']


89
AnyGenes, Paris, France.
[]
['https://ror.org/00k8b3640']


103
Authors' Affiliations: 1Department of Chemistry and Applied Biosciences, Institute of Pharmaceutical Sciences, ETH Zürich; 2Philochem AG, Otelfingen, Zurich, Switzerland; 3Department of Chemistry, University of Cambridge, Cambridge, United Kingdom; and 4Instituto de Medicina Molecular, Faculdade de Medicina da Universidade de Lisboa, Av. Prof. Egas Moniz, Lisboa, Portugal
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/04n35qp23', 'name': 'Institute of Pharmaceutical Sciences', 'confidence': 1.0, 'status': 'active', 'country': 'switzerland'}, {'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/05a28rw58', 'name': 'ETH Zurich', 'confidence': 1.0, 'status': 'active', 'country': 'switzerland'}, {'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/013meh722', 'name': 'University of Cambridge', 'confidence': 1.0, 'status': 'active', 'country': 'united kingdom'}, {'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/01c27hj86', 'name': 'University of Lisbon', 'confidence': 0.6324555320336758, 'status': 'active', 'country': 'portugal'}]
['https://ror.org/05a28rw58', 'https://ror.org/01hp71z51', 'https://ror.org/013meh722', 'https://ror.org/01c27hj86', 'https://ror.org/04n35qp23']


109
Barbara Davis Center for Childhood Diabetes, University
of Colorado Health Sciences, Denver, CO, USA
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/04cqn7d42', 'name': 'University of Colorado Cancer Center', 'confidence': 0.6666666666666666, 'status': 'active', 'country': 'united states'}]
['https://ror.org/02hh7en24']


114
Beijing Neurosurgical Institute, Beijing Tiantan Hospital, Capital Medical University; Beijing, China
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/013xs5b60', 'name': 'Capital Medical University', 'confidence': 1.0, 'status': 'active', 'country': 'china'}]
['https://ror.org/003regz62', 'https://ror.org/013xs5b60']


117
BioTechMed-Graz, Graz, Austria
[]
['https://ror.org/02jfbm483']


119
Biochemistry and Molecular Genetics Service, Hospital Clinic Universitari and IDIBAPS and CIBERehd, Barcelona, Spain
[]
['https://ror.org/054vayn55', 'https://ror.org/03cn6tr16']


120
Biochimie et Physiologie Moléculaire des Plantes, Centre National de la Recherche Scientifique Unité Mixte de Recherche/Institut National de la Recherche Agronomique/SupAgro/Université de Montpellier, Montpellier cedex 1, France
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/02feahw73', 'name': 'Centre National de la Recherche Scientifique', 'confidence': 0.848528137423857, 'status': 'active', 'country': 'france'}, {'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/01x3gbx83', 'name': 'Institut National de la Recherche Agronomique', 'confidence': 1.0, 'status': 'inactive', 'country': 'france'}, {'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/003vg9w96', 'name': "Institut National de Recherche pour l'Agriculture, l'Alimentation et l'Environnement", 'confidence': 1.0, 'status': 'active', 'country': 'france'}, {'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/051escj72', 'name': 'Université de Montpellier', 'confidence': 1.0, 'status': 'active', 'country': 'france'}]
['https://ror.org/03rnk6m14', 'https://ror.org/02feahw73', 'https://ror.org/051escj72']


135
Bone Metabolism Unit, Division of Genetics and Cell Biology, IRCCS San Raffaele Scientific Institute, Milan, Italy;
[]
['https://ror.org/039zxt351']


150
CIRAD, UMR EcoFoG, CNRS, AgroParisTech, INRA; Université des Antilles, Université de Guyane; 97310 Kourou France
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/02feahw73', 'name': 'Centre National de la Recherche Scientifique', 'confidence': 1.0, 'status': 'active', 'country': 'france'}]
['https://ror.org/05kpkpg04', 'https://ror.org/02ryfmr77', 'https://ror.org/02feahw73', 'https://ror.org/04q9vef57', 'https://ror.org/00nb39k71', 'https://ror.org/02kbmgc12']


157
California State University at Hayward 1 Department of Biological Sciences , , Hayward, CA 94542, USA
[]
['https://ror.org/04jaeba88', 'https://ror.org/020qm1538']


160
Canadian Food Inspection Agency (CFIA) National Centres for Animal Disease, Lethbridge Laboratory, P.O. Box 640, Township Road 9-1, Lethbridge, AB T1J 3Z4, Canada.
[]
['https://ror.org/00qxr8t08']


161
Canadian Food Inspection Agency (CFIA) Ontario Laboratory Network, Building 22, 960 Carling Avenue, Ottawa, ON K1A 0C6, Canada.
[]
['https://ror.org/00qxr8t08']


165
Cancer Voices NSW Sydney NSW Australia
[]
['https://ror.org/029a54f25']


168
Cardiovascular Department, MultiMedica Group, Italy
[]
['https://ror.org/01h8ey223']


170
Case Western Reserve University School of Medicine, Cleveland, OH, USA
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/02x4b0932', 'name': 'Cleveland Clinic Lerner College of Medicine', 'confidence': 0.7925939239012172, 'status': 'active', 'country': 'united states'}]
['https://ror.org/051fd9666']


175
Center for
Aerosol and Cloud
Chemistry, Aerodyne Research Inc., Billerica,
Massachusetts 01821, United States
[]
['https://ror.org/01nph4h53']


178
Center for Biologics Evaluation and Research, U.S. Food and Drug Administration, Silver Spring, Maryland 20903, United States
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/02nr3fr97', 'name': 'Center for Biologics Evaluation and Research', 'confidence': 1.0, 'status': 'active', 'country': 'united states'}]
['https://ror.org/034xvzb47', 'https://ror.org/02nr3fr97']


181
Center for Coastal Fisheries and Habitat Research, National Ocean Service, National Oceanic and Atmospheric Administration, Beaufort, NC 28516; and
[]
['https://ror.org/02k4h0334', 'https://ror.org/02z5nhe81']


186
Center for Neurologic Diseases, Brigham and Women's Hospital and Harvard Medical School, 77 Avenue Louis Pasteur, NRB 641, Boston, MA 02115, USA
[]
['https://ror.org/04b6nzv94']


192
Center for disease control and prevention of Henan Province
[]
['https://ror.org/01479r334']


196
Central European Institute of Technology (CEITEC) Masaryk University  Brno Czech Republic
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/03f099r71', 'name': 'Instituts Universitaires de Technologie', 'confidence': 0.6546536707079772, 'status': 'active', 'country': 'france'}]
['https://ror.org/009nz6031']


198
Centre de Recherche en Cancérologie de Marseille (CRCM), CNRS UMR7258, Inserm U1068, Institut Paoli-Calmettes, Aix Marseille Univ, UM105, 13009 Marseille, France
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/035xkbk20', 'name': 'Aix-Marseille Université', 'confidence': 0.5773502691896258, 'status': 'active', 'country': 'france'}, {'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/0494jpz02', 'name': 'Centre de Recherche en Cancérologie de Marseille', 'confidence': 1.0, 'status': 'active', 'country': 'france'}, {'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/04s3t1g37', 'name': 'Institut Paoli-Calmettes', 'confidence': 1.0, 'status': 'active', 'country': 'france'}]
['https://ror.org/0494jpz02', 'https://ror.org/04s3t1g37', 'https://ror.org/035xkbk20', 'https://ror.org/02feahw73']


212
Centre for Structural Biology, VIB, Pleinlaan 2, 1050 Brussels, Belgium
[]
['https://ror.org/03e84cm85']


235
Chongqing Medical University Affiliated Children's Hospital
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/05pz4ws32', 'name': "Children's Hospital of Chongqing Medical University", 'confidence': 0.912870929175277, 'status': 'active', 'country': 'china'}]
['https://ror.org/05pz4ws32', 'https://ror.org/017z00e58']


263
College of Human Ecology, Division of Nutritional Sciences, Cornell University, 412 Savage Hall, Ithaca, NY 14853, USA
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/05bnh6r87', 'name': 'Cornell University', 'confidence': 1.0, 'status': 'active', 'country': 'united states'}]
['https://ror.org/047g2xp14', 'https://ror.org/05bnh6r87']


275
Contained Research Facility, University of California, 555 Hopkins Road, Davis, California 95616, United States
[]
['https://ror.org/05rrcem69']


281
Current Affiliation: Acino AG, Miesbach, Germany
[]
['https://ror.org/00s784a62']


284
DSM Nutritional Products, 4303 Kaiseraugst, Switzerland
[]
['https://ror.org/01fgq8278']


321
Department of Anaesthesia, Poole Hospital NHS Foundation Trust, Poole, UK
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/03kdm3q80', 'name': 'Poole Hospital NHS Foundation Trust', 'confidence': 1.0, 'status': 'inactive', 'country': 'united kingdom'}, {'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/02pa0cy79', 'name': 'University Hospitals Dorset NHS Foundation Trust', 'confidence': 1.0, 'status': 'active', 'country': 'united kingdom'}]
['https://ror.org/00ph04139', 'https://ror.org/02pa0cy79']


328
Department of Anesthesiology, Soryukai Inoue Hospital, Osaka, Japan
[]
['https://ror.org/002g9dc27']


342
Department of Automatic Control, CINVESTAV-IPN, Avenida Instituto Politécnico Nacional 2508, 07360 México, DF, Mexico
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/059sp8j34', 'name': 'Instituto Politécnico Nacional', 'confidence': 0.8660254037844388, 'status': 'active', 'country': 'mexico'}]
['https://ror.org/009eqmr18']


347
Department of Biochemistry and Molecular Genetics, Program in Molecular Biology, University of Colorado Health Sciences Center, Denver, Colorado 80262
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/04cqn7d42', 'name': 'University of Colorado Cancer Center', 'confidence': 0.6666666666666666, 'status': 'active', 'country': 'united states'}]
['https://ror.org/02hh7en24']


355
Department of Bioinformatics, Osaka University Graduate School of Medicine, Osaka, Japan
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/04a8t1e98', 'name': 'Osaka Gakuin University', 'confidence': 0.7745966692414834, 'status': 'active', 'country': 'japan'}]
['https://ror.org/035t8zc32']


373
Department of Biomedical Engineering, Georgia Institute of TechnologyAtlanta, GAUSA
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/01zkghx44', 'name': 'Georgia Institute of Technology', 'confidence': 0.8660254037844388, 'status': 'active', 'country': 'united states'}]
['https://ror.org/02j15s898', 'https://ror.org/01zkghx44']


381
Department of Biostatistics, Arkansas Children’s Hospital Research Institute, University of Arkansas for Medical Sciences, Little Rock, AR 72202, USA
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/00xcryt71', 'name': 'University of Arkansas for Medical Sciences', 'confidence': 1.0, 'status': 'active', 'country': 'united states'}]
['https://ror.org/01t33qq42', 'https://ror.org/00xcryt71']


382
Department of Biostatistics, Johns Hopkins Bloomberg School of Public Health , Baltimore, Maryland , USA
[]
['https://ror.org/00za53h95']


388
Department of Biotechnology, Ural Federal State University, Mira 28, 620002 Ekaterinburg, Russia
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/00fycgp36', 'name': 'Ural State Medical University', 'confidence': 0.6063390625908325, 'status': 'active', 'country': 'rusia'}]
['https://ror.org/00hs7dr46']


428
Department of Clinical Laboratory, The Affiliated Hospital of Qingdao University, Qingdao, Shandong 266061, P.R. China
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/026e9yy16', 'name': 'Affiliated Hospital of Qingdao University', 'confidence': 1.0, 'status': 'active', 'country': 'china'}]
['https://ror.org/026e9yy16', 'https://ror.org/021cj6z65']


437
Department of Clinical Sciences and Community Health, University of Milan, Hematology1 CTMO, Foundation IRCCS Ca' Granda Ospedale Maggiore Policlinico, Milano, Italy
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/00wjc7c48', 'name': 'University of Milan', 'confidence': 1.0, 'status': 'active', 'country': 'italy'}]
['https://ror.org/00wjc7c48', 'https://ror.org/016zn0y21']


460
Department of Dermatology, Huashan Hospital of Fudan University, Shanghai, China
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/013q1eq08', 'name': 'Fudan University', 'confidence': 0.7071067811865475, 'status': 'active', 'country': 'china'}]
['https://ror.org/05201qm87', 'https://ror.org/013q1eq08']


474
Department of Economics, School of Arts and Social Sciences, City, University of London, Northampton Square, London EC1V 0HB, UK
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/04489at23', 'name': 'City, University of London', 'confidence': 1.0, 'status': 'inactive', 'country': 'united kingdom'}]
['https://ror.org/04489at23']


492
Department of Environmental Engineering, Suncheon National University, Suncheon, Jeonnam 540-742, Republic of Korea
[]
['https://ror.org/043jqrs76']


511
Department of Gastroenterology, Amsterdam University Medical Center, location VUMC, Amsterdam, The Netherlands
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/05grdyy37', 'name': 'Amsterdam University Medical Centers', 'confidence': 0.8660254037844388, 'status': 'active', 'country': 'netherlands'}]
['https://ror.org/00q6h8f30', 'https://ror.org/05grdyy37']


546
Department of Histopathology, West Middlesex University Hospital, Chelsea and Westminster NHS Trust, London, United Kingdom
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/05vgg2c14', 'name': 'West Middlesex University Hospital', 'confidence': 1.0, 'status': 'active', 'country': 'united kingdom'}]
['https://ror.org/05vgg2c14', 'https://ror.org/02gd18467']


559
Department of Internal Medicine, Affiliated Dongyang Hospital of Wenzhou Medical University, Dongyang, Zhejiang 322100, China
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/011b9vp56', 'name': "Ruian People's Hospital", 'confidence': 0.8164965809277261, 'status': 'active', 'country': 'china'}]
['https://ror.org/00rd5t069']


560
Department of Internal Medicine, Aging and Kidney Disease Department, Sant'Orsola-Malpighi University Hospital, Poliambulatorio Pad. 2, Via Albertoni 15, 40138 Bologna, Italy
[]
['https://ror.org/00t4vnv68']


622
Department of Mechanical Engineering, Indiana University−Purdue University Indianapolis, Indianapolis, Indiana 46202, United States
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/05gxnyn08', 'name': 'Indiana University – Purdue University Indianapolis', 'confidence': 1.0, 'status': 'inactive', 'country': 'united states'}]
['https://ror.org/01kg8sb98', 'https://ror.org/0482ksk80']


648
Department of Medicine, Weill Cornell Medical College, New York, New York.
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/05v5hg569', 'name': 'Weill Cornell Medical College in Qatar', 'confidence': 0.8944271909999159, 'status': 'active', 'country': 'qatar'}]
['https://ror.org/02r109517']


677
Department of Neurology, The Fifth Affiliated Hospital of Sun Yat-Sen University, Zhuhai 519000, P.R. China
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/023te5r95', 'name': 'Fifth Affiliated Hospital of Sun Yat-sen University', 'confidence': 1.0, 'status': 'active', 'country': 'china'}]
['https://ror.org/023te5r95', 'https://ror.org/0064kty71']


683
Department of Neurosurgery, Kansai Rosai Hospital
[]
['https://ror.org/024ran220']


689
Department of Nuclear Medicine, University Hospital RWTH Aachen
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/02gm5zw39', 'name': 'Universitätsklinikum Aachen', 'confidence': 0.8660254037844388, 'status': 'active', 'country': 'germany'}]
['https://ror.org/02gm5zw39', 'https://ror.org/04xfq0f34']


723
Department of Otorhinolaryngology – Head and Neck Surgery, Central Military Hospital ‘Dr. A. Mathijsen’, Utrecht, The Netherlands
[]
['https://ror.org/01d3gh658']


729
Department of Pathology &amp; Immunology, Washington University School of Medicine, St. Louis, Missouri, USA
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/03ymk3103', 'name': 'University of Washington School of Medicine', 'confidence': 1.0, 'status': 'withdrawn', 'country': 'united states'}, {'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/00cvxb145', 'name': 'University of Washington', 'confidence': 1.0, 'status': 'active', 'country': 'united states'}]
['https://ror.org/037cnag11']


734
Department of Pathology, Saint Antoine Hospital AP-HP, Paris, France
[]
['https://ror.org/01875pg84']


735
Department of Pathology, Stanford University Medical Center, Stanford, CA 94305;
[{'provenance': 'affro', 'version': '3.1.2', 'pid': 'ror', 'value': 'https://ror.org/03mtd9a03', 'name': 'Stanford Medicine', 'confidence': 1.0, 'status': 'active', 'country': 'united states'}]
['https://ror.org/00f54p054', 'https://ror.org/03mtd9a03']


737

In [12]:
run_affro('Biological Science Research Laboratory, Lion Corporation')

[{'provenance': 'affro',
  'version': '3.1.2',
  'pid': 'ror',
  'value': 'https://ror.org/01bt8n520',
  'name': 'Lion Corporation (Japan)',
  'confidence': 1.0,
  'status': 'active',
  'country': 'japan'}]

In [5]:
evaluate_micro(dataset, 'affro_rors_active') #  version (full) ror april replacements all

{'precision': 0.9725158562367865,
 'recall': 0.9175531914893617,
 'f1_score': 0.9442353746151214}

In [8]:
run_affro('university of athens')

[{'provenance': 'affro',
  'version': '3.1.2',
  'pid': 'ror',
  'value': 'https://ror.org/04gnjpq42',
  'name': 'National and Kapodistrian University of Athens',
  'confidence': 1,
  'status': 'active',
  'country': 'greece'}]

In [11]:
run_affro("CAS Key Laboratory of Soft Matter Chemistry, Department of Polymer Science and Engineering, University of Science and Technology of China, Hefei, Anhui Province 230026, P. R. China")

[{'provenance': 'affro',
  'version': '3.1.2',
  'pid': 'ror',
  'value': 'https://ror.org/04c4dkn09',
  'name': 'University of Science and Technology of China',
  'confidence': 1.0,
  'status': 'active',
  'country': 'china'}]

In [10]:
run_affro('department of mathematicsuniversity of athens')

[{'provenance': 'affro',
  'version': '3.1.2',
  'pid': 'ror',
  'value': 'https://ror.org/04gnjpq42',
  'name': 'National and Kapodistrian University of Athens',
  'confidence': 0.5773502691896258,
  'status': 'active',
  'country': 'greece'}]

In [14]:
run_affro('Department of Neurology, Bundang Jesaeng General Hospital, Daejin Medical Center, Seongnam,  Korea')

[{'provenance': 'affro',
  'version': '3.3.1',
  'pid': 'ror',
  'value': 'https://ror.org/03z0bdc81',
  'name': 'Bundang Jesaeng Hospital',
  'confidence': 1.0,
  'status': 'active',
  'country': ['south korea']}]

In [18]:
dataset['raw_affiliation_string'].iloc[110]

'Barbara Davis Center for Diabetes, University of Colorado, Anschutz Medical Campus, Aurora, CO'

In [17]:
run_affro(dataset['raw_affiliation_string'].iloc[110])

[{'provenance': 'affro',
  'version': '3.0.1',
  'pid': 'ror',
  'value': 'https://ror.org/00jc20583',
  'name': 'University of Colorado System',
  'confidence': 1,
  'status': 'active',
  'country': 'united states'}]

In [15]:
dataset[dataset['FN_affro_rors_active']>0][0:20]

,Unnamed: 0,raw_affiliation_string,curated,affro_results,affro_rors_active,TP_affro_rors_active,FP_affro_rors_active,FN_affro_rors_active
10,10,"1Department of Radiation Oncology, Washington ...",[https://ror.org/01yc7t268],"[{'provenance': 'affro', 'version': '3.0.1', '...",[https://ror.org/00cvxb145],0,1,1
53,53,"7Department of Surgery, University of Washingt...",[https://ror.org/01yc7t268],"[{'provenance': 'affro', 'version': '3.0.1', '...",[https://ror.org/00cvxb145],0,1,1
54,54,"7Ludwig Center at Harvard, Boston, Massachusetts.",[https://ror.org/03vek6s52],[],[],0,0,1
59,59,"9Alvin J. Siteman Center, Washington Universit...",[https://ror.org/01yc7t268],"[{'provenance': 'affro', 'version': '3.0.1', '...",[https://ror.org/00cvxb145],0,1,1
65,65,"AFRU711 HPW/RHPB, Wright-Patterson Air Force B...",[https://ror.org/0097e1k27],[],[],0,0,1
67,67,"AMO GmbH, Gesellschaft für Angewandte Mikro- u...",[https://ror.org/01sd0e661],[],[],0,0,1
71,71,"Abdus Salam ICTP, Strada Costiera 11, Trieste ...",[https://ror.org/009gyvm78],[],[],0,0,1
89,89,"AnyGenes, Paris, France.",[https://ror.org/00k8b3640],[],[],0,0,1
103,103,Authors' Affiliations: 1Department of Chemistr...,"[https://ror.org/05a28rw58, https://ror.org/01...","[{'provenance': 'affro', 'version': '3.0.1', '...","[https://ror.org/04n35qp23, https://ror.org/01...",4,0,1
109,109,"Barbara Davis Center for Childhood Diabetes, U...",[https://ror.org/02hh7en24],"[{'provenance': 'affro', 'version': '3.0.1', '...",[https://ror.org/04cqn7d42],0,1,1
110,110,"Barbara Davis Center for Diabetes, University ...","[https://ror.org/03wmf1y16, https://ror.org/00...","[{'provenance': 'affro', 'version': '3.0.1', '...",[https://ror.org/00jc20583],1,0,1
114,114,"Beijing Neurosurgical Institute, Beijing Tiant...","[https://ror.org/003regz62, https://ror.org/01...","[{'provenance': 'affro', 'version': '3.0.1', '...",[https://ror.org/013xs5b60],1,0,1
117,117,"BioTechMed-Graz, Graz, Austria",[https://ror.org/02jfbm483],[],[],0,0,1
119,119,"Biochemistry and Molecular Genetics Service, H...","[https://ror.org/054vayn55, https://ror.org/03...",[],[],0,0,2
120,120,Biochimie et Physiologie Moléculaire des Plant...,"[https://ror.org/03rnk6m14, https://ror.org/02...","[{'provenance': 'affro', 'version': '3.0.1', '...","[https://ror.org/051escj72, https://ror.org/02...",2,1,1
135,135,"Bone Metabolism Unit, Division of Genetics and...",[https://ror.org/039zxt351],[],[],0,0,1
150,150,"CIRAD, UMR EcoFoG, CNRS, AgroParisTech, INRA; ...","[https://ror.org/05kpkpg04, https://ror.org/02...","[{'provenance': 'affro', 'version': '3.0.1', '...",[https://ror.org/02feahw73],1,0,5
157,157,California State University at Hayward 1 Depar...,"[https://ror.org/04jaeba88, https://ror.org/02...",[],[],0,0,2
160,160,Canadian Food Inspection Agency (CFIA) Nationa...,[https://ror.org/00qxr8t08],[],[],0,0,1
161,161,Canadian Food Inspection Agency (CFIA) Ontario...,[https://ror.org/00qxr8t08],[],[],0,0,1

[{'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'ror',
  'value': 'https://ror.org/04qb8nc58',
  'name': 'Clausthal University of Technology',
  'confidence': 1.0,
  'status': 'active',
  'country': ['germany']}]

In [12]:
run_affro('Institut für Organische Chemie Clausthal, Clausthal-Zellerfeld, Deutschland')

[{'provenance': 'affro',
  'version': '3.3.0',
  'pid': 'openorgs',
  'value': 'openorgs____::0000103105',
  'name': 'Institut für Organische Chemie, TU Clausthal',
  'confidence': 1.0,
  'status': 'active',
  'country': ['germany']}]

In [15]:
run_affro('wiliam beaumont hospital, royal oak, usa')

[{'provenance': 'affro',
  'version': '3.3.1',
  'pid': 'ror',
  'value': 'https://ror.org/03artm726',
  'name': 'Beaumont Hospital, Royal Oak',
  'confidence': 1.0,
  'status': 'active',
  'country': ['united states']}]

In [3]:
matchings_affro('Antenna & High Frequency Research Centre, Dublin Institute of Technology Kevin Street, Dublin 8, Ireland')

[('affro',
  '3.0.1',
  'ror',
  'https://ror.org/029nmgq20',
  'Dublin Institute of Technology',
  0.8660254037844388,
  'inactive',
  'ireland'),
 ('affro',
  '3.0.1',
  'ror',
  'https://ror.org/04t0qbt32',
  'Technological University Dublin',
  0.8660254037844388,
  'active',
  'ireland')]

In [4]:
matchings_affro("Osaka Metropolitan University Department of Aerospace Engineering, Graduate School of Engineering, , Sakai,   ,")

[('affro',
  '3.0.1',
  'ror',
  'https://ror.org/01hvx5h04',
  'Osaka Metropolitan University',
  1.0,
  'active',
  'japan')]

In [11]:
run_affro('tu berlin, Deutschland')

[{'provenance': 'affro',
  'version': '3.0.1',
  'pid': 'ror',
  'value': 'https://ror.org/03v4gjf40',
  'name': 'Technische Universität Berlin',
  'confidence': 0.816496580927726,
  'status': 'active',
  'country': 'germany'}]

In [7]:
matchings_affro('Institut für Organische Chemie, Technisches Univer Clausthal')

[('affro',
  '3.0.1',
  'ror',
  'https://ror.org/04qb8nc58',
  'Clausthal University of Technology',
  1.0,
  'active',
  'germany')]

In [8]:
matchings_affro('Institut für Organische Chemie, Clausthal, Clausthal-Zellerfeld, Deutschland')

In [8]:
matchings_affro('Department of Electrical and Electronic Engineering, Intelligent Systems Research Group (ISRG), Near East University, Mersin 10, Türkiye')

In [9]:
matchings_affro('--label omited: 2--maxwel finland laboratory infectious diseases, boston medical center, boston university school medicine, boston, masachusets')

[('affro',
  '3.0.1',
  'ror',
  'https://ror.org/010b9wj87',
  'Boston Medical Center',
  1.0,
  'active',
  'united states'),
 ('affro',
  '3.0.1',
  'ror',
  'https://ror.org/03ps5d564',
  'Boston University School of Medicine',
  1.0,
  'withdrawn',
  'united states'),
 ('affro',
  '3.0.1',
  'ror',
  'https://ror.org/05qwgg493',
  'Boston University',
  1.0,
  'active',
  'united states')]

In [6]:
matchings_affro('selcuk universitesi veteriner fakultesi, patoloji anabilim dali, kampus, konya,turkiye kirgizistan-turkiye manas universitesi, veteriner fakultesi, biskek/kirgizistan')

[('affro',
  '3.0.0',
  'ror',
  'https://ror.org/045hgzm75',
  'Selçuk University',
  0.7071067811865475,
  'active',
  'turkey'),
 ('affro',
  '3.0.0',
  'ror',
  'https://ror.org/04frf8n21',
  'Kyrgyz-Türkish Manas Üniversity',
  0.816496580927726,
  'active',
  'kyrgyzstan')]

In [7]:
matchings_affro("Universita'vjh di pisa")

[('affro',
  '3.0.0',
  'ror',
  'https://ror.org/03ad39j10',
  'University of Pisa',
  0.816496580927726,
  'active',
  'italy')]

In [8]:
matchings_affro('niab, united kingdom')

[('affro',
  '3.0.0',
  'ror',
  'https://ror.org/010jx2260',
  'National Institute of Agricultural Botany',
  1.0,
  'active',
  'united kingdom')]

In [9]:
matchings_affro("google, United Kingdom")

[('affro',
  '3.0.0',
  'ror',
  'https://ror.org/024bc3e07',
  'Google (United Kingdom)',
  1.0,
  'active',
  'united kingdom')]

In [10]:
matchings_affro("Universita'vhj di pisa")

[('affro',
  '3.0.0',
  'ror',
  'https://ror.org/03ad39j10',
  'University of Pisa',
  0.816496580927726,
  'active',
  'italy')]

In [11]:
run_affro('university of athens')

[{'provenance': 'affro',
  'version': '3.0.0',
  'pid': 'ror',
  'value': 'https://ror.org/04gnjpq42',
  'name': 'National and Kapodistrian University of Athens',
  'confidence': 1,
  'status': 'active',
  'country': 'greece'}]